In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('청년정책목록_전체.csv', encoding='utf-8')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3458 entries, 0 to 3457
Data columns (total 60 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   plcyNo             3458 non-null   object
 1   bscPlanCycl        3458 non-null   int64
 2   bscPlanPlcyWayNo   3458 non-null   int64
 3   bscPlanFcsAsmtNo   3458 non-null   int64
 4   bscPlanAsmtNo      3458 non-null   int64
 5   pvsnInstGroupCd    3458 non-null   int64
 6   plcyPvsnMthdCd     623 non-null    float64
 7   plcyAprvSttsCd     3458 non-null   int64
 8   plcyNm             3458 non-null   object
 9   plcyKywdNm         956 non-null    object
 10  plcyExplnCn        3458 non-null   object
 11  lclsfNm            3421 non-null   object
 12  mclsfNm            3421 non-null   object
 13  plcySprtCn         3458 non-null   object
 14  sprvsnInstCd       2464 non-null   object
 15  sprvsnInstCdNm     3440 non-null   object
 16  sprvsnInstPicNm    766 non-null    object
 17  operInstCd         2089 non-null   object
 18  operInstCdNm       2851 non-null   object
 19  operInstPicNm      491 non-null    object
 20  sprtSclLmtYn       3458 non-null   object
 21  aplyPrdSeCd        3458 non-null   int64
 22  bizPrdSeCd         619 non-null    float64
 23  bizPrdBgngYmd      757 non-null    object
 24  bizPrdEndYmd       757 non-null    object
 25  bizPrdEtcCn        1808 non-null   object
 26  plcyAplyMthdCn     2926 non-null   object
 27  srngMthdCn         2044 non-null   object
 28  aplyUrlAddr        1579 non-null   object
 29  sbmsnDcmntCn       2226 non-null   object
 30  etcMttrCn          2175 non-null   object
 31  refUrlAddr1        2557 non-null   object
 32  refUrlAddr2        536 non-null    object
 33  sprtSclCnt         1411 non-null   float64
 34  sprtArvlSeqYn      3458 non-null   object
 35  sprtTrgtMinAge     2453 non-null   float64
 36  sprtTrgtMaxAge     2390 non-null   float64
 37  sprtTrgtAgeLmtYn   3458 non-null   object
 38  mrgSttsCd          638 non-null    float64
 39  earnCndSeCd        615 non-null    float64
 40  earnMinAmt         580 non-null    float64
 41  earnMaxAmt         580 non-null    float64
 42  earnEtcCn          97 non-null     object
 43  addAplyQlfcCndCn   1964 non-null   object
 44  ptcpPrpTrgtCn      1887 non-null   object
 45  inqCnt             3458 non-null   int64
 46  rgtrInstCd         3416 non-null   object
 47  rgtrInstCdNm       3416 non-null   object
 48  rgtrUpInstCd       3416 non-null   object
 49  rgtrUpInstCdNm     3413 non-null   object
 50  rgtrHghrkInstCd    3416 non-null   object
 51  rgtrHghrkInstCdNm  3413 non-null   object
 52  zipCd              3458 non-null   object
 53  plcyMajorCd        3458 non-null   object
 54  jobCd              3458 non-null   object
 55  schoolCd           3458 non-null   object
 56  aplyYmd            2319 non-null   object
 57  frstRegDt          3458 non-null   object
 58  lastMdfcnDt        3458 non-null   object
 59  sbizCd             3458 non-null   object
dtypes: float64(9), int64(8), object(43)
memory usage: 1.6+ MB

In [ ]:
# 정책번호
# 필요없는 컬럼
df['plcyNo']

# plcyNo 중복 데이터 확인
print(f"전체 데이터 수: {len(df)}")
print(f"고유한 plcyNo 수: {df['plcyNo'].nunique()}")

# 중복된 plcyNo 있는지 확인
duplicates = df['plcyNo'].duplicated().sum()
print(f"중복된 plcyNo 개수: {duplicates}")

# 중복된 plcyNo가 있다면 어떤 번호가 중복되었는지 확인
if duplicates > 0:
    duplicate_values = df[df['plcyNo'].duplicated(keep=False)].sort_values('plcyNo')
    print("중복된 plcyNo 값:")
    display(duplicate_values[['plcyNo']])

전체 데이터 수: 3458
고유한 plcyNo 수: 3458
중복된 plcyNo 개수: 0

# 기본계획

In [27]:
# 기본계획차수, 기본계획정책방향번호, 기본계획중점과제번호, 기본계획과제번호
df[['bscPlanCycl', 'bscPlanPlcyWayNo', 'bscPlanFcsAsmtNo', 'bscPlanAsmtNo']]

      bscPlanCycl  bscPlanPlcyWayNo  bscPlanFcsAsmtNo  bscPlanAsmtNo
0               1                 3                10             23
1               1                 4                14             35
2               1                 4                15             39
3               1                 4                13             32
4               1                 4                13             32
...           ...               ...               ...            ...
3453            1                 4                15             40
3454            1                 2                 6             13
3455            1                 1                 2              4
3456            1                 3                10             23
3457            1                 1                 1              1

[3458 rows x 4 columns]

In [31]:
# 기본계획차수
df['bscPlanCycl'].value_counts()

bscPlanCycl
1    3458
Name: count, dtype: int64

In [32]:
# 기본계획정책방향번호
df['bscPlanPlcyWayNo'].value_counts()

bscPlanPlcyWayNo
1    1387
4     806
3     446
2     440
5     379
Name: count, dtype: int64

In [33]:
# 기본계획중점과제번호
df['bscPlanFcsAsmtNo'].value_counts()

bscPlanFcsAsmtNo
1     751
2     435
6     251
15    241
16    227
13    178
10    168
14    160
17    140
11    130
19    108
3     107
9     101
4      94
5      83
20     72
18     59
8      57
7      49
12     47
Name: count, dtype: int64

In [34]:
# 기본계획과제번호
df['bscPlanAsmtNo'].value_counts()

bscPlanAsmtNo
1     348
2     330
4     257
13    235
5     178
39    152
42    124
32    120
23    106
45     94
40     89
50     80
28     77
3      73
10     65
33     58
6      57
43     57
8      57
34     56
7      50
35     48
41     46
44     46
25     46
52     44
19     38
9      37
18     36
27     35
36     31
21     28
51     28
49     28
15     27
20     22
17     21
48     21
38     20
46     20
11     18
26     18
47     18
29     16
12     16
24     16
30     16
31     15
22     13
16     12
14     10
37      5
Name: count, dtype: int64

In [ ]:
# 기본계획 데이터들이 필요한가?

# 제공기관그룹

In [36]:
# 제공기관그룹코드
df['pvsnInstGroupCd'].value_counts()
# 지자체, 정부?

pvsnInstGroupCd
54002    3038
54001     420
Name: count, dtype: int64

# 정책

In [39]:
# 정책제공방법코드, 정책승인상태코드, 정책명, 정책키워드명, 정책설명내용, 정책지원내용, 정책신청방법내용
df[['plcyPvsnMthdCd', 'plcyAprvSttsCd', 'plcyNm', 'plcyKywdNm', 'plcyExplnCn', 'plcySprtCn', 'plcyAplyMthdCn']].head(5)

,plcyPvsnMthdCd,plcyAprvSttsCd,plcyNm,plcyKywdNm,plcyExplnCn,plcySprtCn,plcyAplyMthdCn
0,42013.0,44002,주거안정장학금,"보조금,교육지원",원거리 대학 진학으로 인해 주거 관련 비용 부담이 큰 저소득 대학생을 대상으로 주거...,"□ 지원금액: 월 최대 20만 원\n※ 단, 방학 중(7~8월, 1~2월)에는 지원...",□ 2학기 신청일정: 2025. 5. 23.(금) 9시 ~ 6. 23.(월) 18시...
1,42010.0,44002,부산 청년돌봄이음,바우처,고립·은둔 청년 및 가족돌봄 청(소)년 지원,"1. 청년 돌봄이음 시범사업(제공기관 : 종합사회복지관) : 초기상담, 성장 계획 ...",부산사회서비스원 홈페이지온라인 신청\n○ 고립은둔 청년 지원 신청 : https:/...
2,42005.0,44002,서울 청년 마음건강 지원사업,맞춤형상담서비스,우울·불안 등 정서적 어려움을 겪는 청년의 마음건강 회복,ㅇ (사업 내용) 2단계 선별검사로 과학적 진단을 통한 맞춤형 상담 지원\n ...,"총 4차(1월, 4월, 6월, 9월)에 걸쳐 참여자를 모집하며, 연도내 중복참여는 ..."
3,42005.0,44002,희망두배 청년통장,금리혜택,"학자금 대출, 주거비, 비정규직 취업 등으로 어려움을 겪고 있는 청년의 자립지원을 ...",□ 본인저축액 : 월 15만원\n□ 매칭지원액 : 본인저축액과 동일한 금액 매월 적...,□ 신청기간 : 2025. 6. 9.(월) ~ 6. 20.(금) 18:00 ※ 신청...
4,42002.0,44002,서울 영테크,맞춤형상담서비스,청년 금융교육 및 재무상담을 통한 경제적 자립 지원,"무료 재무상담(대면, 비대면) 및 금융교육, 커뮤니티 운영\nㅇ (재무상담) 재무진...",NaN

In [40]:
# 정책제공방법코드
df['plcyPvsnMthdCd'].value_counts()

plcyPvsnMthdCd
42006.0    165
42013.0    163
42002.0    141
42004.0     46
42001.0     33
42010.0     31
42005.0     24
42011.0      9
42003.0      5
42007.0      4
42012.0      1
42008.0      1
Name: count, dtype: int64

In [ ]:
# 정책승인상태코드
# 필요없는 컬럼
df['plcyAprvSttsCd'].value_counts()

plcyAprvSttsCd
44002    3458
Name: count, dtype: int64

In [ ]:
# 정책키워드명
# ,로 구분된 키워드 분리작업 필요

# 분류

In [44]:
# 정책대분류명, 정책중분류명
df[['lclsfNm', 'mclsfNm']]

          lclsfNm                 mclsfNm
0              교육                   교육비지원
1            복지문화             취약계층 및 금융지원
2            복지문화                      건강
3            복지문화             취약계층 및 금융지원
4            복지문화             취약계층 및 금융지원
...           ...                     ...
3453    복지문화,복지문화          취약계층 및 금융지원,건강
3454        주거,주거  주택 및 거주지,전월세 및 주거급여 지원
3455      일자리,일자리                   취업,창업
3456  일자리,교육,복지문화   취업,미래역량강화,취약계층 및 금융지원
3457          일자리                      취업

[3458 rows x 2 columns]

In [46]:
# 정책대분류명, 중분류명 ,로 구분된 키워드 분리작업 필요

# 주관기관

In [ ]:
# 주관기관코드, 주관기관코드명, 주관기관담당자명
# 주관기관코드, 주관기관담당자명 컬럼 필요 없음
df[['sprvsnInstCd', 'sprvsnInstCdNm', 'sprvsnInstPicNm']]

     sprvsnInstCd sprvsnInstCdNm sprvsnInstPicNm
0         1342000            교육부             NaN
1         6260000          부산광역시             NaN
2         6114551        청년사업담당관             김진희
3         6114679        돌봄고독정책관       돌봄복지과 윤동민
4         6114551        청년사업담당관             이지원
...           ...            ...             ...
3453      1383000          여성가족부             NaN
3454      1613039    국토교통부 주택기금과             NaN
3455      1721000      과학기술정보통신부             NaN
3456      5080341     구미시청 인구청년과             NaN
3457                   강릉시 경제진흥과             손고은

[3458 rows x 3 columns]

In [49]:
# 주관기관코드명 값 확인
# 고유한 주관기관코드명의 개수 확인
print(f"주관기관코드명(sprvsnInstCdNm)의 고유 값 개수: {df['sprvsnInstCdNm'].nunique()}")

# 각 값의 출현 빈도 확인
sprvsnInstCdNm_counts = df['sprvsnInstCdNm'].value_counts()
print(f"상위 20개 주관기관코드명:")
display(sprvsnInstCdNm_counts.head(20))

# 하나의 정책만 가진 기관 수 확인
single_policy_institutions = sprvsnInstCdNm_counts[sprvsnInstCdNm_counts == 1].count()
print(f"하나의 정책만 가진 기관 수: {single_policy_institutions}")

주관기관코드명(sprvsnInstCdNm)의 고유 값 개수: 1720
상위 20개 주관기관코드명:

sprvsnInstCdNm
고용노동부            83
보건복지부            42
충청북도             37
전북특별자치도          32
-                29
국토교통부            28
전라남도             25
경상북도             23
교육부              23
경기도              23
중소벤처기업부          23
서울특별시            22
전북특별자치도 익산시      20
인천광역시 청년정책담당관    19
서산시              18
전북청년허브센터         17
부산진구             17
청년정책과            17
경상남도             17
문화체육관광부          16
Name: count, dtype: int64

하나의 정책만 가진 기관 수: 1252

In [ ]:
# 주관기관코드명 분포 시각화
import matplotlib.pyplot as plt
import seaborn as sns

# 상위 15개 기관만 시각화
plt.figure(figsize=(12, 6))
sns.barplot(x=sprvsnInstCdNm_counts.head(15).index, y=sprvsnInstCdNm_counts.head(15).values)
plt.title('상위 15개 주관기관별 정책 수')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# 정책 수에 따른 기관 분포
policy_count_distribution = sprvsnInstCdNm_counts.value_counts().sort_index()
plt.figure(figsize=(10, 6))
sns.barplot(x=policy_count_distribution.index.astype(str), y=policy_count_distribution.values)
plt.title('정책 수에 따른 기관 분포')
plt.xlabel('기관당 정책 수')
plt.ylabel('기관 수')
plt.tight_layout()
plt.show()