In [161]:
import pandas as pd 

df = pd.read_csv("청년정책목록_전체.csv")

# 모듈 불러오기

In [162]:
import importlib
import dataprocessing_module 
importlib.reload(dataprocessing_module)
from dataprocessing_module import *

# 불필요 컬럼 제거

In [163]:
df = drop_columns(df)

# 컬럼영어 -> 한글로 변환

In [164]:
df = rename_columns_kor(df)

In [155]:
df.columns.to_list()

['정책번호',
 '정책제공방법코드',
 '정책명',
 '정책키워드명',
 '정책설명내용',
 '정책대분류명',
 '정책중분류명',
 '정책지원내용',
 '주관기관코드명',
 '운영기관코드명',
 '신청기간구분코드',
 '사업기간구분코드',
 '사업기간시작일자',
 '사업기간종료일자',
 '사업기간기타내용',
 '정책신청방법내용',
 '심사방법내용',
 '신청URL주소',
 '제출서류내용',
 '기타사항내용',
 '참고URL주소',
 '참고URL주소',
 '지원도착순서여부',
 '지원대상최소연령',
 '지원대상최대연령',
 '결혼상태코드',
 '소득조건구분코드',
 '소득기타내용',
 '추가신청자격조건내용',
 '참여제안대상내용',
 '조회수',
 '정책거주지역코드',
 '정책전공요건코드',
 '정책취업요건코드',
 '정책학력요건코드',
 '신청기간',
 '정책특화요건코드']

# 신청기간 지난거 지우기

In [165]:
df_filtered = filter_valid_application_periods(df)

c:\dev\github\SKN10-FINAL-5Team\data\dataprocessing_module.py:83: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[biz_end_col] = pd.to_datetime(df[biz_end_col], errors='coerce')

In [166]:
df_filtered['신청기간']

0       20250523 ~ 20250623
1                       NaN
3       20250609 ~ 20250620
4       20250301 ~ 20251130
6                       NaN
               ...
3452                    NaN
3453                    NaN
3454                    NaN
3455                    NaN
3456                    NaN
Name: 신청기간, Length: 1209, dtype: object

In [167]:
df_filtered['정책명']

0                         주거안정장학금
1                       부산 청년돌봄이음
3                       희망두배 청년통장
4                          서울 영테크
6                    부산 청년 소셜 다이닝
                  ...
3452                  학교 밖 청소년 지원
3453                학교 밖 청소년 건강검진
3454          중소기업 취업청년 전월세보증금 대출
3455    초고속 정보통신기반 인력양성(2년제 학위과정)
3456     [구미시] 전입 고등학생, 대학생 학업장려금
Name: 정책명, Length: 1209, dtype: object

In [150]:
print(df_filtered[['지원대상최소연령', '지원대상최대연령']].dtypes)

지원대상최소연령    float64
지원대상최대연령    float64
dtype: object

In [168]:
 # 3. 나이 필터링 (18~39세 이내 또는 NaN)
df_age_filtered = remove_age_outliers(df_filtered)

In [172]:
df_age_filtered['정책명']

0                부산 청년돌봄이음
1                희망두배 청년통장
2                   서울 영테크
3             부산 청년 소셜 다이닝
4             부산 청년활동 마일리지
              ...
560           청년전용 버팀목전세자금
561          청년전용 보증부 월세대출
562                 청년도약계좌
563       청년 소상공인 창업응원금 지원
564    중소기업 취업청년 전월세보증금 대출
Name: 정책명, Length: 565, dtype: object

In [198]:
from dotenv import load_dotenv

In [199]:
import os

In [200]:
load_dotenv()
api_key = os.getenv("API_KEY")

In [173]:
# 4. 정책대분류명 분류 (주거, 일자리(교육), 기타)
df_category = add_category_column(df_age_filtered,api_key)

100%|██████████| 565/565 [14:45<00:00,  1.57s/it]

In [174]:
df_category['정책대분류명'].value_counts()

정책대분류명
일자리(교육)    316
기타         182
주거          67
Name: count, dtype: int64

In [175]:
df_category.head()

,정책번호,정책제공방법코드,정책명,정책키워드명,정책설명내용,정책대분류명,정책중분류명,정책지원내용,주관기관코드명,운영기관코드명,...,참여제안대상내용,조회수,정책거주지역코드,정책전공요건코드,정책취업요건코드,정책학력요건코드,신청기간,정책특화요건코드,신청시작일,신청마감일
0,20250520005400210862,42010.0,부산 청년돌봄이음,바우처,고립·은둔 청년 및 가족돌봄 청(소)년 지원,기타,취약계층 및 금융지원,"1. 청년 돌봄이음 시범사업(제공기관 : 종합사회복지관) : 초기상담, 성장 계획 ...",부산광역시,NaN,...,NaN,16,"26110,26140,26170,26200,26230,26260,26290,2632...",0011009,0013010,0049010,NaN,0014010,NaT,NaT
1,20250519005400210852,42005.0,희망두배 청년통장,금리혜택,"학자금 대출, 주거비, 비정규직 취업 등으로 어려움을 겪고 있는 청년의 자립지원을 ...",기타,취약계층 및 금융지원,□ 본인저축액 : 월 15만원\n□ 매칭지원액 : 본인저축액과 동일한 금액 매월 적...,돌봄고독정책관,NaN,...,NaN,475,"11110,11140,11170,11200,11215,11230,11260,1129...",0011009,0013001,0049010,20250609 ~ 20250620,0014009,2025-06-09,2025-06-20
2,20250519005400210851,42002.0,서울 영테크,맞춤형상담서비스,청년 금융교육 및 재무상담을 통한 경제적 자립 지원,일자리(교육),취약계층 및 금융지원,"무료 재무상담(대면, 비대면) 및 금융교육, 커뮤니티 운영\nㅇ (재무상담) 재무진...",청년사업담당관,NaN,...,NaN,26,"11110,11140,11170,11200,11215,11230,11260,1129...",0011009,0013010,0049010,20250301 ~ 20251130,0014010,2025-03-01,2025-11-30
3,20250517005400210839,42002.0,부산 청년 소셜 다이닝,교육지원,공통의 관심사를 가진 청년들이 전문가와 함께 음식을 만들고 식사를 하며 자연스러운 ...,기타,"청년참여,정책인프라구축","- 모집인원 : 프로그램 회차별 8명(2인 1조, 총 4개조)\n- 장 소 : 부산...",부산광역시,NaN,...,NaN,42,"26110,26140,26170,26200,26230,26260,26290,2632...",0011009,0013010,0049010,NaN,0014010,NaT,NaT
4,20250517005400210838,42002.0,부산 청년활동 마일리지,교육지원,청년들의 다양한 시정 참여 활동에 마일리지를 부여하여 청년들의 자발적인 정책 참여를...,기타,"청년참여,정책인프라구축","부산 시정 참여에 따른 마일리지는 포인트(동백전)으로 부여, 연 최대 10만 포인트...",부산광역시,NaN,...,NaN,11,"26110,26140,26170,26200,26230,26260,26290,2632...",0011009,0013010,0049010,NaN,0014010,NaT,NaT

In [177]:
# 5. 정책세부분류명 분류 (분야별 세분류)
df_category = add_subcategory_column(df_category, api_key)

세부분류 중: 100%|██████████| 383/383 [09:54<00:00,  1.55s/it]

In [178]:
df_category.head(3)

,정책번호,정책제공방법코드,정책명,정책키워드명,정책설명내용,정책대분류명,정책중분류명,정책지원내용,주관기관코드명,운영기관코드명,...,조회수,정책거주지역코드,정책전공요건코드,정책취업요건코드,정책학력요건코드,신청기간,정책특화요건코드,신청시작일,신청마감일,정책세부분류명
0,20250520005400210862,42010.0,부산 청년돌봄이음,바우처,고립·은둔 청년 및 가족돌봄 청(소)년 지원,기타,취약계층 및 금융지원,"1. 청년 돌봄이음 시범사업(제공기관 : 종합사회복지관) : 초기상담, 성장 계획 ...",부산광역시,NaN,...,16,"26110,26140,26170,26200,26230,26260,26290,2632...",0011009,0013010,0049010,NaN,0014010,NaT,NaT,기타
1,20250519005400210852,42005.0,희망두배 청년통장,금리혜택,"학자금 대출, 주거비, 비정규직 취업 등으로 어려움을 겪고 있는 청년의 자립지원을 ...",기타,취약계층 및 금융지원,□ 본인저축액 : 월 15만원\n□ 매칭지원액 : 본인저축액과 동일한 금액 매월 적...,돌봄고독정책관,NaN,...,475,"11110,11140,11170,11200,11215,11230,11260,1129...",0011009,0013001,0049010,20250609 ~ 20250620,0014009,2025-06-09,2025-06-20,기타
2,20250519005400210851,42002.0,서울 영테크,맞춤형상담서비스,청년 금융교육 및 재무상담을 통한 경제적 자립 지원,일자리(교육),취약계층 및 금융지원,"무료 재무상담(대면, 비대면) 및 금융교육, 커뮤니티 운영\nㅇ (재무상담) 재무진...",청년사업담당관,NaN,...,26,"11110,11140,11170,11200,11215,11230,11260,1129...",0011009,0013010,0049010,20250301 ~ 20251130,0014010,2025-03-01,2025-11-30,기타

In [179]:

# 6. 정책 텍스트 정제 및 요약
df_final = apply_preprocessing_to_df(df_category, api_key)

텍스트 정제 중: 100%|██████████| 565/565 [39:50<00:00,  4.23s/it]

In [181]:
df_final['정책지원내용']

0      1. 청년 돌봄이음 시범사업: 초기상담, 성장 계획 작성 및 모니터링, 자조모임, ...
1      - 본인저축액: 월 15만원  \n- 매칭지원액: 본인저축액과 동일한 금액 매월 적...
2      - 무료 재무상담: 대면 및 비대면 방식으로 재무진단, 소득지출관리, 투자관리, 신...
3      - 모집인원: 프로그램 회차별 8명(2인 1조, 총 4개조)  \n- 장소: 부산청...
4      부산 시정 참여에 따라 연 최대 10만 포인트(동백전)를 지원하며, 시정홍보, 봉사...
                             ...
560    - 대출금리: 연 1.8~2.7%  \n- 대출한도: 호당 2억원 이하(만 25세 ...
561    - 대출금리: 보증금 연 1.3%, 월세금 연 0% (20만원 한도), 1.0% (...
562    가입자의 소득구간 및 월 납입액에 따라 최대 6%의 정부기여금을 지원하며, 본인 납...
563    - 창업응원금: 기업당 30만원 지원(1회, 현금 지급)\n- 교육지원: 창업 관련...
564    - 대출금리: 연 1.5%  \n- 대출한도: 최대 1억원  \n- 대출기간: 최초...
Name: 정책지원내용, Length: 565, dtype: object

# 코드 매핑

In [182]:
from preprocessing import *

In [186]:
import openpyxl
df_all, df_code, df_region, df_region2 = load_all_datasets()

In [187]:
 # 2. 일반 코드 컬럼 매핑
code_columns = get_matching_code_columns(df_final, df_code)

In [188]:
df_final = apply_code_mappings(df_final, df_code, code_columns)

     원래 코드    매핑된 이름
0  42010.0       바우처
1  42005.0  계약(위탁운영)
2  42002.0      프로그램
3  42002.0      프로그램
4  42002.0      프로그램
   원래 코드 매핑된 이름
0  57002     상시
1  57001   특정기간
2  57001   특정기간
3  57002     상시
4  57002     상시
     원래 코드 매핑된 이름
0  56001.0   특정기간
1  56001.0   특정기간
2  56001.0   특정기간
3  56001.0   특정기간
4  56001.0   특정기간
     원래 코드 매핑된 이름
0  55003.0   제한없음
1  55003.0   제한없음
2  55003.0   제한없음
3  55003.0   제한없음
4  55003.0   제한없음
     원래 코드 매핑된 이름
0  43003.0     기타
1  43003.0     기타
2  43001.0     무관
3  43001.0     무관
4  43001.0     무관

In [189]:
 # 3. 특수 요건 코드 필드 매핑
df_final = map_all_code_fields(df_final, df_code)

--------------------------------------------------
전공조건코드 매핑 시작...
정책전공요건코드: 총 565개 중 565개 매핑 완료 (100.00%)

--------------------------------------------------
자격학력코드 매핑 시작...
정책학력요건코드: 총 565개 중 565개 매핑 완료 (100.00%)

--------------------------------------------------
취업상태코드 매핑 시작...
정책취업요건코드: 총 565개 중 565개 매핑 완료 (100.00%)

--------------------------------------------------
특수분야코드 매핑 시작...
정책특화요건코드: 총 565개 중 565개 매핑 완료 (100.00%)

In [190]:
    # 4. 지역 코드 매핑 - 법정동 기준
region_code_map = create_region_code_map(df_region2)
df_final = apply_region_code_mapping(
    df_final,
    column="정책거주지역코드",
    transform_func=lambda x: transform_region_code(x, region_code_map)
)

In [191]:
# 5. 정책거주지역코드 → 대표지역명으로 통합
df_final = map_region_to_representative(df_final, column_name="정책거주지역코드")

'경상남도 창원시'으로 변경된 행 수: 1
'전라남도'으로 변경된 행 수: 2
'충청북도'으로 변경된 행 수: 10
'전북특별자치도'으로 변경된 행 수: 4
'경기도'으로 변경된 행 수: 2
'경상북도'으로 변경된 행 수: 1
'경상남도'으로 변경된 행 수: 2

In [196]:
  # 7. 결과 저장
save_dataframe(df_final, filename="청년정책목록_전체_매핑_전처리완료", filetype="excel")

In [197]:
save_dataframe(df_final, filename="청년정책목록_전체_매핑_전처리완료", filetype="csv", encoding="euc-kr")

UnicodeEncodeError: 'euc_kr' codec can't encode character '\u2027' in position 84: illegal multibyte sequence