In [90]:

import pandas as pd

# CSV 파일 불러오기
df = pd.read_csv("청년정책_주거세부분류추가_final.csv")

In [91]:
df_housing = df[df['정책대분류'] == '주거'].copy()

In [172]:
len(df_housing)

332

In [92]:
# 대출만 추출
df_loan = df_housing[df_housing['주거세부분류'] == '대출'].copy()

In [93]:
# 전월세만 추출
df_rent = df_housing[df_housing['주거세부분류'] == '전월세'].copy()

In [94]:
# 보조금만 추출
df_grant = df_housing[df_housing['주거세부분류'] == '보조금'].copy()

In [95]:
# 기타 (대출/전월세/보조금 외 나머지)
df_etc = df_housing[df_housing['주거세부분류'] == '기타'].copy()

In [96]:
# 결과 미리 보기
print("대출 정책 수:", len(df_loan))
print("전월세 정책 수:", len(df_rent))
print("보조금 정책 수:", len(df_grant))
print("기타 정책 수:", len(df_etc))

대출 정책 수: 76
전월세 정책 수: 195
보조금 정책 수: 10
기타 정책 수: 51

In [97]:
print(df_loan['정책명'])

22                 청년 주택드림 디딤돌 대출
35              신혼부부 주거자금 대출이자 지원
212          신혼부부 전세자금 대출이자 지원 사업
225             신혼부부 주택자금 대출이자 지원
346          신혼부부 주택 전세자금 대출이자 지원
                  ...
3283    신혼부부 전월세자금 대출이자 지원사업(광주시)
3428                     주거안정월세대출
3430                청년전용 보증부 월세대출
3436               신생아 특례 전세자금 대출
3461          중소기업 취업청년 전월세보증금 대출
Name: 정책명, Length: 76, dtype: object

In [98]:
print(df_rent['정책명'])

19                       대전청년하우스
113      2025 북구 청년 창업자 임대료 지원사업
125                청년안심주택 공급(매입)
127            전월세 안심계약 도움서비스 운영
128                     청년 월세 지원
                  ...
3391                   청년 이사비 지원
3393    2024년 자립준비청년(청년 유형) 전세임대
3421     2024년 청년기업 안정화 임대료 지원사업
3427                 신혼부부전용 전세자금
3429                청년전용 버팀목전세자금
Name: 정책명, Length: 195, dtype: object

In [99]:
print(df_grant['정책명'])

0                          주거안정장학금
24                속초시 청년 이사비용 지원사업
216           청년취업자 및 청년농업인 주거비 지원
404                 모다드림 청년통장 지원사업
490            장흥군 신혼부부 웨딩포토비 지원사업
492                  신혼부부 이사비 지원사업
496              강진품애 청년 주거비 지원 사업
506     청년 및 주거취약계층 주택 중개수수료 지원 사업
1031                 해남형 청년 주거비 지원
3204    대학생 주거 지원(서서울관, 동서울관, 청주관)
Name: 정책명, dtype: object

In [100]:
print(df_etc['정책명'])

3                                      희망두배 청년통장
4                                         서울 영테크
33                            부산 자립청년 주거 다 지원 사업
34                                    부산청년 머물자리론
92                                 미래두배 청년통장(대전)
129                           신혼부부 청년 임차보증금 지원사업
190                                   청년주택드림청약통장
337                            신혼(예비)부부 건강검진비 지원
535                      부산진구 청년1인가구 주거환경개선 프로그램
842                    2024년 강원도 주거비 지원 장학생 추가모집
876     경북 상주시 청년 주거 임차비 지원사업(지역 정착 창업사업 참여자 대상)
1017                              미혼청년 주거급여 분리지급
1022                              강진품애 청년 주거비 지원
1028                           고흥 청년 디딤돌 주거안정 지원
1199                                   으뜸관악 청년통장
1202                           양평愛 청년통장 6기 (양평군)
1289                           영암형 공공주택(청년·신혼부부)
1295                  울산 신혼, 맞벌이부부 행복 공동육아나눔터 확충
1334                             울산 청년 주거급여 분리지급
1479                          울산 동구 청년 주거급여 분리지급
1493                        울산 중구 청년 주거상담소 지정 운영
1502                   2024년 남원시 청년주거비 지원사업 추가모집
1561                           울산 남구 청년주거급여 분리지급
1597                    울산 남구 신혼부부 건강검진 및 산전기초검사
1601                 경남 1인가구 및 취약계층 세대 주거환경수리서비스
1610                          신혼부부학교 신청자 모집(평택시)
1657                                   든든한주거복지기금
1680                           경남 모다드림 청년통장 지원사업
1842                         울산 신혼부부 가구 주거비 지원사업
1848                       울산 울주군 신혼부부 주거비용 지원사업
1864    청년·신혼 희망터치(Touch) 보증금 이자지원 사업 추가 모집(수원시)
1889                      관외 대학생 주거안정비 지원사업(안성시)
2008                         1939 청년 주거 클래스(구리시)
2189                          신혼부부 청년 임차보증금 지원사업
2255                           주거비지원 장학생 선발(화성시)
2421                       김해시 신혼 첫 주택 리모델링 지원사업
2553                           법률용어특강 '주거편'(수원시)
2561                      애향 및 주거지원 장학생 선발(동두천시)
2744                               서울시 희망두배 청년통장
2809                                청년 주거 임차비 지원
2857                          [서천군]청년 행복주거비 지원사업
2888                                 서울 영테크 지원사업
2963          청년·신혼 희망터치(Touch) 보증금 이자지원 사업(수원시)
2981                              미혼청년 주거급여 분리지급
3082                        성남시 취업청년 주거안심 패키지 사업
3102                             진안군 청년 주거비 지원사업
3123                군산 STAY 청년창업 주거지원사업 참여자 모집공고
3138                           울산 청년가구 주거비 지원 사업
3222                                  청년 주거급여 지원
3309                              [대전] 미래두배 청년통장
3416                                청년 주택드림 청약통장
Name: 정책명, dtype: object

In [101]:
# 대출 관련 정책 대상에 따라 조건 보기
def classify_target(text):
    if pd.isna(text):
        return '기타'
    elif '신혼' in text or '신혼부부' in text:
        return '신혼부부'
    elif '청년' in text:
        return '청년'
    else:
        return '기타'

In [102]:
# '정책명' 기준으로 대상 분류
df_loan['대상유형'] = df_loan['정책명'].apply(classify_target)

In [103]:
# 확인
print(df_loan['대상유형'].value_counts())

대상유형
신혼부부    51
청년      19
기타       6
Name: count, dtype: int64

In [104]:
# 청년 대상 대출
df_loan_youth = df_loan[df_loan['대상유형'] == '청년']
print(df_loan_youth[['정책명', '정책지원내용']])

                                     정책명  \
22                        청년 주택드림 디딤돌 대출
579                      서천군 청년 행복주거비 지원
863   2024년 부산시 머물자리론 (청년전세대출 대출이자지원 사업)
883   2024년 3차 군포시 청년 전월세 보증금 대출이자 지원 안내
914               대구시 청년 희망주택 대출이자 지원 사업
1101             청년 주거자금 대출이자 지원(경남 산청군)
1503         청년 전월세보증금 대출이자 지원 추가모집(평택시)
1519         청년 전·월세 보증금 대출이자 지원사업 (화성시)
1527            청년 전월세 보증금 대출이자 지원 (군포시)
1537         하반기 안양시 청년 전월세보증금 대출이자 지원사업
1814                 거창군 청년 전세자금 대출이자 지원
2366                   청년 전월세 보증금대출이자 지원
2646           청년 전월세 보증금 대출이자 지원사업(화성시)
2658              청년 전월세보증금 대출이자 지원(평택시)
2722      상반기 청년 전ㆍ월세 보증금 대출이자 지원사업(안양시)
3094           군포시 청년 전월세 보증금 대출이자 지원 공고
3109                용인청년 전·월세보증금 대출이자 지원
3430                       청년전용 보증부 월세대출
3461                 중소기업 취업청년 전월세보증금 대출

                                                                                                                                                                                                                                                                                                                                                        정책지원내용
22                         □ 대출금리 : 2.4% ~ 4.15%\n□ 대출한도 : 다음 중 작은 금액으로 산정\n  - 미혼 3억원, 신혼 4억원 이내(LTV 70%, 생애최초 주택구입자는 LTV 80%, DTI 60% 이내)\n  - 분양가격 이내로 하되, 대출총액은 (본건 내집마련 디딤돌 대출 + 국민주택건설자금 + 중도금대출 + 기금대출)은 매매가격 초과 불가\n  - 대출금액 = [(담보주택 평가액 × LTV) – 선순위채권 – 임대보증금 및 최우선변제소액임차보증금]\n□ 대출기간 : 10년, 15년, 20년, 30년(연소득 4천만원 이하는 만기 40년 이용 가능)(거치 1년 또는 비거치)
579                                                                                                                                                                                                                                                                   서천군에 주소를 둔 18세~45세 무주택 세대주 청년에게 전·월세, 주택 구입 등에 따른 주거비를 월15만원에서 가구원수에 따라 최대 29만원까지 2년간 지원
863   소득별 이자 차등 지원\n* 미혼인 경우 본인 연소득, 기혼인 경우 부부합산 연소득 기준\n- 대출취급은행 : 부산은행\n- 대출기간 : 1년 이상, 2년 이내로서 당해 임대차 계약 만료일까지\n* 임대차 계약기간이 1년인 경우, 대출 실행 시 대출기간이 1년 미만이 되므로 신청 불가\n- 대출최대한도 : 1억원 이내(임차보증금의 90% 범위 내 → 나머지 본인 부담)\n* 실제 대출가능금액은 금융기관(한국주택금융공사, 부산은행) 제 규정에 따라 다르며, 부산시 자격요건에 해당되어 선정되더라도 부산은행과 한국주택금융공사에서 대출(보증)심사 및 신용평가, 소득심사는 별도 실시하며 그 결과에 따라 제외될 수 있음
883                                                                                                                                                                                                                                                                                                                                 전월세 보증금 대출잔액의 1%, 최대 100만원
914                                                                                                                     전세자금 대출자를 대상으로 표준임대보증금 범위내에서 대출이자 50% 지원\n임대보증금이 표준임대보증금을 초과할 경우 표준임대보증금 부족분에 대한 지원대상 대출금액 이자 50% 지원\n표준임대보증금, 월임대료 등은 입주자 모집공고문에서 확인\n이자지원 금리는 정부의 전세자금 대출상품인 버팀목 전세자금(1.8~2.4%) 대출금리 적용\n※ 버팀목 외 대출자는 전세자금 대출금리와 버팀목 최대금리 중 낮은 금리 적용
1101                                                                                                                                                                                                                                                               주거자금(주택 신축 구입, 임차) 대출이자지원(대출잔액의 1.5%이내)\n    - 최대금액: 출산가정 1,500천원, 신혼부부 1,000천원, 전입세대 500천원
1503                                                                                                                                                                        ○ 지원내용 : 연 최대 200만 원 / 최대 24개월 / 생애 1회\n - 연 2회 지급/ 1회 지급 금액은 청구 시 대출 잔액의 1%(1회 최대 100만 원\n○ 지급방법 : 신청인 명의 계좌 입금(연 2회/ 매년 1, 7월 지급)\n ※ 최초 지원은 10월 지급, 이후 지원은 기존 대상자와 동일 지급(1, 7월)
1519                                                                                                                                                                                                                                       □ 지원내용: 연 최대 200만원 (대출액의 연 2% 이자지원. 대출이율이 2% 이하일 경우 실질 대출금리 적용)\n - 연 1회, 생애 최대 2회 신청 가능 (원금 중도 상환 시 대출액 평균의 2% 적용)
1527                                                                                                                                                                              □ 지원내용: 전월세 보증금 대출잔액의 1%, 최대 100만원\n  ※ 임대차계약기간 내 금융기관 서류의 대출실행 유지 기간(월/당해 연도) 일시금 지급\n    예) 임대차계약기간 및 대출기간: 2024년 2월 1일 ~ 2026년 2월 1일\n     · 2024년도 대출이자 지원사업 신청 11개월분 지원
1537                                                                                                                                                                     □ 지원내용 : 전월세보증금에 대한 신규 대출 추천 및 신규 대출 실행 시 연 2% 이내 이자 지원\n(대출금리) 6개월 MOR(시장금리) + 1.5%, 변동금리\n(대출한도) 최대 2억원 이내(임차보증금의 90% 이내) \n(대출기간) 2년, 1회 연장 가능(최대 4년) \n※ 자세한 내용은 붙임문서를 참고하시기 바랍니다
1814                                                                                                                                                                                                   주택 전세 자금 대출 잔액의 1.5% 이내에서 지급하되, 대출 기간 남은 개월수에 따라 차등 지급\n※ 단, 지원내용이 중복될 경우 하나만 지원\n- 출산가정 : 최대 지원금액 150만원\n- 신혼부부 : 최대 지원금액 100만원\n- 전입세대 : 최대 지원금액 50만원
2366                                                                                                                                                                                                                 □ 전월세 보증금 대출이자 \n ㅇ 전월세 보증금 대출이자 4.5%이내 전액\n ㅇ 대출한도 전세(1억원), 월세(5천만원) 이내 지원\n□  주택구입 대출이자 지원\n ㅇ 주택구입 대출이자 4.5%이내 전액\n ㅇ 대출한도 1.5억원 이내 지원
2646                                                                                                                                                                                                                                        ○ 지원내용: 대출액의 연2% 이자 지원 (최대 200만원)\n  ※ 연 1회, 생애 최대 2회 신청 가능\n  ※ 기본요건과 소득요건을 충족한 경우, 이전 거주했던 주택(주택기준 충족)에 대해 신청 가능
2658                                                                                                                                                                                                                     ○ 지원내용 : 연 최대 200만 원 / 최대 24개월 / 생애 1회\n  - 연 2회 지급/ 1회 지급 금액은 청구 시 대출 잔액의 1%(1회 최대 100만 원)\n○ 지급방법 : 신청인 명의 계좌 입금(연 2회/ 매년 1, 7월 지급)
2722                                                                                                                                                                                                                                                     - 전월세보증금 신규 대출추천(최대 2억원 이내) 및 연 2% 이내 이자지원\n- 문의 : 안양시 청년정책관(031-8045-5787), NH농협 안양시지부(031-380-0863)
3094                                                                                                                                                                              □ 지원내용: 전월세 보증금 대출잔액의 1%, 최대 100만원\n  ※ 임대차계약기간 내 금융기관 서류의 대출실행 유지 기간(월/당해 연도) 일시금 지급\n    예) 임대차계약기간 및 대출기간: 2024년 2월 1일 ~ 2026년 2월 1일\n     · 2024년도 대출이자 지원사업 신청 11개월분 지원
3109                                                                                                                                                                                                                                                                                           전월세 보증금 대출잔액의 1% 범위 내 이자 지원 (최대 100만원)\n\n지급방법\n- 신청인 본인명의 계좌입금
3430                                                                                                                                                       □  대출금리\n(보증금) 연 1.3%,(월세금) 연0%(20만원 한도), 1.0% (20만원 초과)\n※ 자산심사 부적격자의 경우 가산금리가 부과\n□ 대출한도\n(보증금) 최대 3,500만원 이내 (월세금) 최대 1,200만원 (24개월 기준 월 50만원 이내) \n□ 대출기간\n25개월 만기 일시상환(4회 연장, 최장 10년 5개월 이용가능)
3461                                                                                                                                                                                                                                                                                   □ 대출금리 : 연 1.5%\n□ 대출한도 : 최대 1억원 이내\n□ 대출기간 : 최초 2년(4회 연장, 최장 10년 이용가능)

In [105]:
# 1. '대출이자'가 들어가는 경우
df_loan_youth_with_interest = df_loan_youth[df_loan_youth['정책명'].str.contains('대출이자', na=False)]

In [106]:
# 2. '대출이자'가 들어가지 않는 경우
df_loan_youth_without_interest = df_loan_youth[~df_loan_youth['정책명'].str.contains('대출이자', na=False)]

In [107]:
print(df_loan_youth_without_interest[['정책명']])

                      정책명
22         청년 주택드림 디딤돌 대출
579       서천군 청년 행복주거비 지원
3430        청년전용 보증부 월세대출
3461  중소기업 취업청년 전월세보증금 대출

In [108]:
# 확인
print("대출이자 포함:", len(df_loan_youth_with_interest))
print("대출이자 미포함:", len(df_loan_youth_without_interest))

대출이자 포함: 15
대출이자 미포함: 4

In [109]:
# 컬럼 안의 텍스트를 줄임 없이 출력
pd.set_option('display.max_colwidth', None)

# 예시: 청년 대상 대출이자 정책의 정책지원내용 전체 출력
df_loan_youth_with_interest[['정책지원내용','심사방법내용']]

# 선정 기준은 소득 기준으로 보는데 소득 기준은 데이터에 거의 없고, 홈페이지 확인해야함

,정책지원내용,심사방법내용
863,"소득별 이자 차등 지원\n* 미혼인 경우 본인 연소득, 기혼인 경우 부부합산 연소득 기준\n- 대출취급은행 : 부산은행\n- 대출기간 : 1년 이상, 2년 이내로서 당해 임대차 계약 만료일까지\n* 임대차 계약기간이 1년인 경우, 대출 실행 시 대출기간이 1년 미만이 되므로 신청 불가\n- 대출최대한도 : 1억원 이내(임차보증금의 90% 범위 내 → 나머지 본인 부담)\n* 실제 대출가능금액은 금융기관(한국주택금융공사, 부산은행) 제 규정에 따라 다르며, 부산시 자격요건에 해당되어 선정되더라도 부산은행과 한국주택금융공사에서 대출(보증)심사 및 신용평가, 소득심사는 별도 실시하며 그 결과에 따라 제외될 수 있음",NaN
883,"전월세 보증금 대출잔액의 1%, 최대 100만원",○ 발 표 일: 2024. 12. 19.(목) 문자메시지(EMS) 개별 통보\n○ 지 급 일: 2024. 12. 20.(금)
914,"전세자금 대출자를 대상으로 표준임대보증금 범위내에서 대출이자 50% 지원\n임대보증금이 표준임대보증금을 초과할 경우 표준임대보증금 부족분에 대한 지원대상 대출금액 이자 50% 지원\n표준임대보증금, 월임대료 등은 입주자 모집공고문에서 확인\n이자지원 금리는 정부의 전세자금 대출상품인 버팀목 전세자금(1.8~2.4%) 대출금리 적용\n※ 버팀목 외 대출자는 전세자금 대출금리와 버팀목 최대금리 중 낮은 금리 적용","○ 지급시기\n증빙자료 확인 후 분기별 지급(3월, 6월, 9월, 12월)"
1101,"주거자금(주택 신축 구입, 임차) 대출이자지원(대출잔액의 1.5%이내)\n - 최대금액: 출산가정 1,500천원, 신혼부부 1,000천원, 전입세대 500천원",NaN
1503,"○ 지원내용 : 연 최대 200만 원 / 최대 24개월 / 생애 1회\n - 연 2회 지급/ 1회 지급 금액은 청구 시 대출 잔액의 1%(1회 최대 100만 원\n○ 지급방법 : 신청인 명의 계좌 입금(연 2회/ 매년 1, 7월 지급)\n ※ 최초 지원은 10월 지급, 이후 지원은 기존 대상자와 동일 지급(1, 7월)","선정방법 : 가구원 수, 소득, 임차보증금, 차량시가표준액 기준\n 심사표에 따라 총점이 높은 순으로 우선 선정"
1519,"□ 지원내용: 연 최대 200만원 (대출액의 연 2% 이자지원. 대출이율이 2% 이하일 경우 실질 대출금리 적용)\n - 연 1회, 생애 최대 2회 신청 가능 (원금 중도 상환 시 대출액 평균의 2% 적용)",□ 결과통보: 신청인 개별 문자 통보
1527,"□ 지원내용: 전월세 보증금 대출잔액의 1%, 최대 100만원\n ※ 임대차계약기간 내 금융기관 서류의 대출실행 유지 기간(월/당해 연도) 일시금 지급\n 예) 임대차계약기간 및 대출기간: 2024년 2월 1일 ~ 2026년 2월 1일\n · 2024년도 대출이자 지원사업 신청 11개월분 지원",□ 발 표 일: 2024. 9. 12.(목) 문자메시지(EMS) 개별 통보\n□ 지 급 일: 2024. 9. 13.(금)
1537,"□ 지원내용 : 전월세보증금에 대한 신규 대출 추천 및 신규 대출 실행 시 연 2% 이내 이자 지원\n(대출금리) 6개월 MOR(시장금리) + 1.5%, 변동금리\n(대출한도) 최대 2억원 이내(임차보증금의 90% 이내) \n(대출기간) 2년, 1회 연장 가능(최대 4년) \n※ 자세한 내용은 붙임문서를 참고하시기 바랍니다",NaN
1814,"주택 전세 자금 대출 잔액의 1.5% 이내에서 지급하되, 대출 기간 남은 개월수에 따라 차등 지급\n※ 단, 지원내용이 중복될 경우 하나만 지원\n- 출산가정 : 최대 지원금액 150만원\n- 신혼부부 : 최대 지원금액 100만원\n- 전입세대 : 최대 지원금액 50만원",공고문 참고
2366,"□ 전월세 보증금 대출이자 \n ㅇ 전월세 보증금 대출이자 4.5%이내 전액\n ㅇ 대출한도 전세(1억원), 월세(5천만원) 이내 지원\n□ 주택구입 대출이자 지원\n ㅇ 주택구입 대출이자 4.5%이내 전액\n ㅇ 대출한도 1.5억원 이내 지원",□ 수시 개별연락
2646,"○ 지원내용: 대출액의 연2% 이자 지원 (최대 200만원)\n ※ 연 1회, 생애 최대 2회 신청 가능\n ※ 기본요건과 소득요건을 충족한 경우, 이전 거주했던 주택(주택기준 충족)에 대해 신청 가능",선정방법: 공고문의 배점표에 따라 총점 고득점자 순으로 우선 선정
2658,"○ 지원내용 : 연 최대 200만 원 / 최대 24개월 / 생애 1회\n - 연 2회 지급/ 1회 지급 금액은 청구 시 대출 잔액의 1%(1회 최대 100만 원)\n○ 지급방법 : 신청인 명의 계좌 입금(연 2회/ 매년 1, 7월 지급)","- 예비 선정일/ 선정인원 : 2024. 6. 14.(금) (예정)/ 예비 전정 110명\n- 최종 선정일/ 선정인원 : 2024. 6. 28.(금) (예정)/ 최종 선정 100명 ※ 예산 범위 내 추가 지원 가능(지원 인원의 10% 이내, 예산 소진 시까지)\n- 발표방법 : 시 홈페이지 게시 및 개별 통보\n ※ 소득·재산 조사 지연 등에 의해 상기 일정은 변경될 수 있음"
2722,"- 전월세보증금 신규 대출추천(최대 2억원 이내) 및 연 2% 이내 이자지원\n- 문의 : 안양시 청년정책관(031-8045-5787), NH농협 안양시지부(031-380-0863)",NaN
3094,"□ 지원내용: 전월세 보증금 대출잔액의 1%, 최대 100만원\n ※ 임대차계약기간 내 금융기관 서류의 대출실행 유지 기간(월/당해 연도) 일시금 지급\n 예) 임대차계약기간 및 대출기간: 2024년 2월 1일 ~ 2026년 2월 1일\n · 2024년도 대출이자 지원사업 신청 11개월분 지원",○ 발 표 일: 2024. 4. 4.(목) 문자메시지(EMS) 개별 통보\n○ 지 급 일: 2024. 4. 5.(금)
3109,전월세 보증금 대출잔액의 1% 범위 내 이자 지원 (최대 100만원)\n\n지급방법\n- 신청인 본인명의 계좌입금,"선정자 발표 (개별 문자 통보) , 4월 중"

In [110]:
# 신혼부부부 대상 대출
df_loan_bubu = df_loan[df_loan['대상유형'] == '신혼부부']
print(df_loan_bubu[['정책명', '정책지원내용']])
# len(df_loan_bubu)

                                                   정책명  \
35                                   신혼부부 주거자금 대출이자 지원
212                               신혼부부 전세자금 대출이자 지원 사업
225                                  신혼부부 주택자금 대출이자 지원
346                               신혼부부 주택 전세자금 대출이자 지원
401                              신혼부부 주택전세자금 대출이자 지원사업
493                                       신혼부부 주거지원 사업
549                        곡성군 청년, 신혼부부 주택자금 대출이자 지원사업
554                               신혼부부 주택 전세자금 대출이자 지원
591              2024년 신혼부부 및 청년 전월세 대출이자 지원사업 공고(10차)
687                 신혼부부·청년 전·월세대출 보증금 이자 지원사업 추가모집 안내
690              2024년 제3차 강남구 신혼부부 및 청년 전월세 대출이자 지원사업
700             2024년 2차 서초구 신혼부부·청년 전월세 보증금 대출이자 지원사업
813     2024년 이천시 청년 신혼부부 주택전월세자금 대출이자 지원 사업 대상자 모집 공고
893   2024년 여주시 청년 신혼부부 주택 전세자금 대출이자 지원 사업 대상자 추가 모집공고
894               2024년 신혼부부 및 청년 전월세 대출이자 지원계획 공고(9차)
934                          의성군 신혼부부 주거비용 지원(인구늘리기시책)
995                            신혼부부 주거자금 대출이자 지원사업(3차)
1048                     동두천시 신혼부부 청년 전월세보증금 대출이자 지원사업
1121                      밀양시 신혼부부 주택구입 대출이자 지원사업(하반기)
1200                 신혼부부 전세자금 대출이자 지원 대상자 모집 2차 (안산시)
1201                  청년 신혼부부 주택 전월세자금 대출이자 지원사업 (양평군)
1220                            청년 및 신혼부부 주거자금 대출이자 지원
1258                      신혼부부 및 청년 전월세 대출이자 지원사업(강남구)
1282                   신혼부부 무주택자 전월세 보증금 대출이자 지원 (군포시)
1368                      신혼부부 주택임차보증금 대출이자 지원사업 (의왕시)
1644                  2차 구리시 무주택 신혼부부 전월세자금 대출이자 지원 사업
1710                   울산 중구 신혼부부 주택 전세자금 대출이자 지원(하반기)
1813                             김해시 신혼부부 전세자금 대출이자 지원
1816                           신혼부부 전세대출금 이자지원 사업(시흥시)
1843                   울산 중구 신혼부부 주택 전세자금 대출이자 지원(상반기)
1849                  울산 울주군 신혼부부 주택 매입·전세자금 대출이자 지원사업
1880                           창원시 신혼부부 주택구입 대출이자 지원사업
1882                     김해시 상·하반기 신혼부부 주택구입 대출이자 지원사업
1915                               신혼부부 주거자금 대출이자 지원사업
2129                거제시 신혼부부 및 미혼모·부 주택 전세자금 대출이자 지원사업
2147                           진주시 신혼부부 주택구입 대출이자 지원사업
2167                  남해군 청년 및 신혼부부 주거자금 대출이자 지원사업(2차)
2348                         신혼부부 전월세자금 대출이자 지원사업(하남시)
2388                     신혼부부 전세자금 대출이자 지원 사업(2차)(용인시)
2404                      거제시 신혼부부 주택구입 대출이자 지원사업(상반기)
2517                               신혼부부 주택전세자금 대출이자 지원
2557                       무주택 신혼부부 전월세자금 대출이자 지원(구리시)
2632                      상반기 신혼부부 주택전세자금 대출이자 지원(과천시)
2670              신혼부부 주택매입 및 전세자금 대출이자 지원' 2차 모집(안양시)
2822                           함안군 신혼부부 주택구입 대출이자 지원사업
2825                      남해군 신혼부부 주택구입 대출이자 지원사업(상반기)
2827                           밀양시 신혼부부 주택구입 대출이자 지원사업
3070                        신혼부부 및 청년 전월세 대출이자 지원(광명시)
3103                                 신혼부부 전세자금 대출이자 지원
3127                 완주군 청년·신혼부부·다자녀가구 주택 전세자금 대출이자 지원
3283                         신혼부부 전월세자금 대출이자 지원사업(광주시)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              정책지원내용
35                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       신혼부부 가구 전·월세 대출금 이자 상환액 지원(대출잔액 1억원 한도 내, 최대 연 3.0%, 최대 2년)
212                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ❍ 지원대상 : 2020년 이후「주택도시기금 신혼부부 전용 전세자금」신규 또는 추가대출 계약자로서, 대출자의 주민등록 및 임차(전세)주택 주소지가 대구인 신혼부부와 예비부부\n❍ 지원금액 : 월별 대출금액에 대하여 자녀수에 따라 차등 이자지원(무자녀 0.5%, 1자녀 1%, 2자녀 이상 1.6%)\n❍ 지원한도 : 신청자가 은행에 납입한 이자액 범위 내 \n❍ 지원기간 : 기본 2년, 최장 6년간 지원(2년마다 갱신 신청)\n❍ 지급방법 : 지원신청 후 반기별 청구에 의거 분할 지급(연2회)
225                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           금융기관으로부터 받은 신혼부부 명의의 주택구입 또는 전세자금 목적의 대출이자 연 1회, 연 최대 100만원을 최대 3년간 연속하여 지원\n ※ 단, 지원금 최초 신청일로부터 2년 이내에 출산하여 가족관계증명서를 제출하는 경우 2년간 추가지원
346                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       지원내용: 전세자금 대출잔액의 1.5% 이내 지원, 연 1회 최대 150만원
401                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ❍ 사업규모 : 100백만원(시비) / 150가구\n ❍ 사업내용 : ⌜주택도시기금⌟ 주택전세자금 대출 이자 지원\n   - 월 최대 10만원 / 4년간 / 반기별 지급(7, 12월) \n ❍ 사업대상\n    (연 령) 부부 모두 순천시에 주소를 둔 만18세~45세 무주택 신혼부부(혼인신고\n              5년 이내)\n    (소 득) 부부합산 연소득 7,500만원 이하(외벌이 5,000만원 이하)\n    (주 택) 순천시 소재 주택, 전세가격 3억원 이하, 전용면적 85㎡ 이하
493                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ❍ 지원대상\n   - 신청일 기준 혼인신고일부터 장흥군 주소등록한 혼인기간 5년 이내 및 중위소득 200% 이하 신혼부부\n   ※ (제외대상) 1가구 다주택자, 국가 또는 지자체 주거 관련 지원중인 자 지급 부적합 사유 발생 시 해당 월까지 지급\n ❍ 지원내용\n   - 유형\n    * 주택구입 및 전세 대출 이자지원 : 기간 3년, 연대출 이자의 50%이내 지원(연 최대 100만원) \n      반기별 지급\n    * 임대주택(월세) 주거비 지원 : 기간 1년, 월 임대료 50%이내(월 최대 10만원) 반기별 지급\n    * 주택정비 지원 : 1회, 정비비용 100만원 이내 지원
549   곡성군에 거주하는 청년 및 신혼부부에게 주택자금(전세, 매매) 대출이자 납부액 연 최대 100만 원씩 2년간 지원\n  1. 신청자격 (아래 가 ~ 마 요건을 모두 충족하여야 함)\n    가. (주    소) 신청일 기준, 곡성군에 주소를 두고 6개월 이상 계속 거주\n       - 곡성군 소재 주택을 전세&middot;매매하고, 그 주택에 주소를 두어야 함\n       - 신혼부부의 경우 부부 모두 곡성군에 주소를 두고 거주\n    나. (무 주 택) 본인 및 가구 구성원 모두가 무주택\n       - 무주택이란 한국주택금융공사 등 대출심사를 받은 주택 외에 다른 주택(분양권 포함)을 소유하지 않은 것을 의미\n    다. (사업대상) 주택자금(전세&middot;매매)용 대출을 받은 청년 또는 신혼부부\n      - 청    년 : 만 19세 이상 49세 이하 청년\n      - 신혼부부 : 최초 사업 신청일 기준, 부부 모두 만 19세 이상 49세 이하이고 혼인신고 이후 5년이 경과하지 않은 신혼부부\n    라. (소득기준)\n      - 청     년 : 가구소득 인정액이 기준중위소득 180% 이하인 자\n      - 신혼부부 : 부부합산 연소득 8,000만원 이하\n    마. (대상주택)\n      - 주택가격 4억 원 이하, 전세 보증금 2억 5천만 원 이하인 관내 주택\n      - 주거전용면적 100㎡이하\n       ※ 주택법상의 단독&middot;다중&middot;다가구&middot;아파트&middot;다세대연립주택&middot;오피스텔
554                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ▪ 지원대상 : 부부합산 연소득 기준 중위소득 180% 이하 가구\n▪ 지원기준 : 부부 중 1명이 청년(18세 ~ 39세) \n▪ 지원내용 : 전세자금 대출잔액의 2.5% 이내(최대 100만원), 연1회(최대2년) 지원\n
591                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             대출금 1억5천만원 범위에서\n－신혼부부 : 전세 2.5%이내, 월세 2.7%이내 (연간 최대 125~135만원 이내)\n－청년 : 전세 1.2%이내, 월세 1.4%이내 (연간 최대 60~70만원 이내)\n지원횟수 : 최대 가구당 3회 지원(매년 1회에 한해 지원)
687                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           동두천시에 주소를 두고 있는 신혼부부·청년에게 1회 1백만 원 한도,\n전세대출 잔액의 1.5% 이내 금액을 현금으로 지급\n(현재 예산소진액 까지만 추가 지원 예정\n청년5가구/ 신혼부부6가구 신혼부부 1가구는 예산 관계로 1백만원 미만 지급 될 수 있으며\n초과 지원시에는 붙임의 배점표에 따른 배점순위에 따른 지급 예정)
690                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ❍ 지원내용\n- 신혼부부 : 대출금 1억 5천만원 범위에서\n대출금의 전세 1% 이내, 월세 1% 이내 (가구 당 최대 연 150만 원 이\n내)\n- 청 년 : 대출금 1억원 범위에서\n대출금의 전세 1% 이내, 월세 1% 이내(가구 당 최대 연 100만 원 이\n내)\n❍ 지원횟수 : 연 1회, 최대 가구 당 3년 지원\n※ 신규지원자 우선 선정 후 연장지원자 선정\n※ 기 지원가구도 매년 신청하여 선정되어야 지원가능
700                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ▢ 세부내용\n - 신혼부부 : 대출 잔액의 연 2%이내 (최대 300만원 / 매년) ＊ 신혼부부의 경우 소득수준 및 자녀 수에 따라 차등지급\n - 청 년 : 대출 잔액의 연 2%이내 (최대 100만원 / 매년)\n ※ 초과 접수될 경우, 가점배점표를 통해 지원결정\n▢ 지원횟수 : 연 1회, 가구 당 최대 3년 지원\n ※ 신규지원자 우선 선정 후 연장지원자 선정되므로, 기 지원가구도 매년 신청하여 선정되어야 지원가능. ▢ 지급방식 : 신청인의 명의 계좌 입금\n▢ 선정통보 : 2024. 12월
813                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2023. 10.~2024. 9. 기간 동안 실제 납부한 주택 전월세자금 대출이자 지원 (대출잔액의 2%, 최대 200만원까지)
893                                                                                                                                                                                                                                                                                                                                              1. 지원금액 : 금융권에서 대출받은 주택 전세자금의 매월 대출 잔액의 연2%를 연간 최대 2백만원까지 지원(천원 미만 절사)\n2. 지원내용 : 2023년 7월 ~ 2024년 6월 기간 동안 납부한 이자\n              (기 납부한 이자가 12개월 미만인 경우에도 지원)\n3. 우대지원 : 유자녀가구(1인당), 장애인, 다문화가구에 대하여 본인이 지출한 이자 범위내에서 매월 대출잔액의 연0.2% 가산지원(대상자   중복 가산 불가)\n     - 지원금과 가산금을 합하여 연 최대 200만원까지 지원\n4. 대출기간이 1년 미만인 경우 최대 지원 가능한 금액 산정\n       (연 최대 200만원÷12개월×대출금 상환한 개월 수)\n5. 지급방식 : 신청인 계좌 입금\n6. 지 급 일 : 2024. 11월 중 (선정자 개별 안내)\n   ※ 지급일은 상기 일정에 따라 변동될 수 있음.
894                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ❍ 지원내용 : 대출금 1억 5천만원 범위에서\n   - 신혼부부 : 대출금의 전세 2.5% 이내, 월세 2.7% 이내 (최대 125 ~ 135만 원)\n   - 청    년 : 대출금의 전세 1.2% 이내, 월세 1.4% 이내 (최대 60 ~ 70만 원)\n❍ 지원횟수 : 연 1회, 가구 당 최대 3년\n※ 기지원가구도 매년 신청하여 선정되어야 지원 가능
934                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          · 신청기간: 혼인신고일로부터 6개월 이내\n· 지원금액: 최대 240만원\n- 2년간 월 10만원 이내 전세자금 대출금 이자 또는 월세자금 지원\n※ 상반기 7월, 하반기 12월 지급
995                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 신혼부부 가구 전·월세 대출금 이자 상환액 지원(최대 연 3.0%)\n ⇨ 대출잔액 1억 원 한도 내, 대출이자 납부 범위 내 지원\n\n- 지원기간 : 최대 2년\n- 지급방법 : 연 1회 지급 * 기 납부한, 상환이자 정산지원
1048                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    지원내용 : 동두천시에 주소를 두고 있는 신혼부부, 청년에게 1회 1백만원 한도, 전세대출 원금의 1~1.5% 이내 금액을 현금으로 지급
1121                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            □ 지원내용   \n○ 지원내용: 주택구입 대출잔액(5천만원 한도)의 3% 이내 지원(반기 별 최대 75만원) \n○ 지원금액: 2024년 1월 ~ 2024년 6월까지 납부한 이자 금액(최대 75만원)\n○ 지급방법: 지원대상자 계좌입금
1200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ㅁ 지원금액 : 전세자금 대출 잔액의 1.5% (최대 130만원) \nㅁ 지원횟수 : 연 1회, 최대 5년간 지원(기 지원 가구도 매년 신규신청)\nㅁ 대상주택: 안산시 소재 전용면적 85㎡ 전세전환가액 3억원 이하 주택 \n※ 기타 자세한 사항은 공고문 확인 필수

In [111]:
# 1. '대출이자'가 들어가는 경우
df_loan_bubu_with_interest = df_loan_bubu[df_loan_bubu['정책명'].str.contains('대출이자', na=False)]

In [112]:
# 2. '대출이자'가 들어가지 않는 경우
df_loan_bubu_without_interest = df_loan_bubu[~df_loan_bubu['정책명'].str.contains('대출이자', na=False)]

In [113]:
# 확인
print("대출이자 포함:", len(df_loan_bubu_with_interest))
print("대출이자 미포함:", len(df_loan_bubu_without_interest))

대출이자 포함: 47
대출이자 미포함: 4

In [114]:
# 컬럼 안의 텍스트를 줄임 없이 출력
pd.set_option('display.max_colwidth', None)

# 예시: 청년 대상 대출이자 정책의 정책지원내용 전체 출력
df_loan_bubu_with_interest[['정책지원내용','심사방법내용']]

,정책지원내용,심사방법내용
35,"신혼부부 가구 전·월세 대출금 이자 상환액 지원(대출잔액 1억원 한도 내, 최대 연 3.0%, 최대 2년)",NaN
212,"❍ 지원대상 : 2020년 이후「주택도시기금 신혼부부 전용 전세자금」신규 또는 추가대출 계약자로서, 대출자의 주민등록 및 임차(전세)주택 주소지가 대구인 신혼부부와 예비부부\n❍ 지원금액 : 월별 대출금액에 대하여 자녀수에 따라 차등 이자지원(무자녀 0.5%, 1자녀 1%, 2자녀 이상 1.6%)\n❍ 지원한도 : 신청자가 은행에 납입한 이자액 범위 내 \n❍ 지원기간 : 기본 2년, 최장 6년간 지원(2년마다 갱신 신청)\n❍ 지급방법 : 지원신청 후 반기별 청구에 의거 분할 지급(연2회)","❍ 지원 대상자 선정 : 수시 심사 및 승인\n❍ 이자지원 : 상반기(5~6월), 하반기(11~12월) 심사 후 지급"
225,"금융기관으로부터 받은 신혼부부 명의의 주택구입 또는 전세자금 목적의 대출이자 연 1회, 연 최대 100만원을 최대 3년간 연속하여 지원\n ※ 단, 지원금 최초 신청일로부터 2년 이내에 출산하여 가족관계증명서를 제출하는 경우 2년간 추가지원",NaN
346,"지원내용: 전세자금 대출잔액의 1.5% 이내 지원, 연 1회 최대 150만원",NaN
401,"❍ 사업규모 : 100백만원(시비) / 150가구\n ❍ 사업내용 : ⌜주택도시기금⌟ 주택전세자금 대출 이자 지원\n - 월 최대 10만원 / 4년간 / 반기별 지급(7, 12월) \n ❍ 사업대상\n (연 령) 부부 모두 순천시에 주소를 둔 만18세~45세 무주택 신혼부부(혼인신고\n 5년 이내)\n (소 득) 부부합산 연소득 7,500만원 이하(외벌이 5,000만원 이하)\n (주 택) 순천시 소재 주택, 전세가격 3억원 이하, 전용면적 85㎡ 이하","❍ 자격요건(적격 심사)\n - (연 령) 부부 모두 순천시에 주소를 둔 만18세~45세 무주택 신혼부부(혼인신고 5년 이내)\n - (소 득) 부부합산 연소득 7,500만원 이하(외벌이 5,000만원 이하)\n - (주 택) 순천시 소재 주택, 전세가격 3억원 이하, 전용면적 85㎡ 이하\n ※&amp;amp;lsquo;주택도시기금&amp;amp;rsquo;의 주택전세자금대출 상품"
549,"곡성군에 거주하는 청년 및 신혼부부에게 주택자금(전세, 매매) 대출이자 납부액 연 최대 100만 원씩 2년간 지원\n 1. 신청자격 (아래 가 ~ 마 요건을 모두 충족하여야 함)\n 가. (주 소) 신청일 기준, 곡성군에 주소를 두고 6개월 이상 계속 거주\n - 곡성군 소재 주택을 전세&middot;매매하고, 그 주택에 주소를 두어야 함\n - 신혼부부의 경우 부부 모두 곡성군에 주소를 두고 거주\n 나. (무 주 택) 본인 및 가구 구성원 모두가 무주택\n - 무주택이란 한국주택금융공사 등 대출심사를 받은 주택 외에 다른 주택(분양권 포함)을 소유하지 않은 것을 의미\n 다. (사업대상) 주택자금(전세&middot;매매)용 대출을 받은 청년 또는 신혼부부\n - 청 년 : 만 19세 이상 49세 이하 청년\n - 신혼부부 : 최초 사업 신청일 기준, 부부 모두 만 19세 이상 49세 이하이고 혼인신고 이후 5년이 경과하지 않은 신혼부부\n 라. (소득기준)\n - 청 년 : 가구소득 인정액이 기준중위소득 180% 이하인 자\n - 신혼부부 : 부부합산 연소득 8,000만원 이하\n 마. (대상주택)\n - 주택가격 4억 원 이하, 전세 보증금 2억 5천만 원 이하인 관내 주택\n - 주거전용면적 100㎡이하\n ※ 주택법상의 단독&middot;다중&middot;다가구&middot;아파트&middot;다세대연립주택&middot;오피스텔",1. 서류심사\n ❍ 접수서류를 기초로 신청자격 충족 여부 및 신청 제외대상 여부 확인\n 2. 대상자 선정\n ❍ 선정방법 : 자격요건에 부합하는 경우\n ❍ 통보방법 : 선정자 개별 통보\n ❍ 신청인원이 초과될 경우 예산 범위 내에서 [배점기준표]를 기준으로 우선순위에 따라 선정
554,"▪ 지원대상 : 부부합산 연소득 기준 중위소득 180% 이하 가구\n▪ 지원기준 : 부부 중 1명이 청년(18세 ~ 39세) \n▪ 지원내용 : 전세자금 대출잔액의 2.5% 이내(최대 100만원), 연1회(최대2년) 지원\n",NaN
591,"대출금 1억5천만원 범위에서\n－신혼부부 : 전세 2.5%이내, 월세 2.7%이내 (연간 최대 125~135만원 이내)\n－청년 : 전세 1.2%이내, 월세 1.4%이내 (연간 최대 60~70만원 이내)\n지원횟수 : 최대 가구당 3회 지원(매년 1회에 한해 지원)",NaN
690,"❍ 지원내용\n- 신혼부부 : 대출금 1억 5천만원 범위에서\n대출금의 전세 1% 이내, 월세 1% 이내 (가구 당 최대 연 150만 원 이\n내)\n- 청 년 : 대출금 1억원 범위에서\n대출금의 전세 1% 이내, 월세 1% 이내(가구 당 최대 연 100만 원 이\n내)\n❍ 지원횟수 : 연 1회, 최대 가구 당 3년 지원\n※ 신규지원자 우선 선정 후 연장지원자 선정\n※ 기 지원가구도 매년 신청하여 선정되어야 지원가능","❍ 지급방식 : 신청인의 명의 계좌 입금\n※ 대출 기간이 2024년 1년(12개월)이 되지 않을 경우 기 납부한 대출이자\n또는 향후 납부 할 대출이자 기준으로 지원금 지급(월단위로 환산)\n❍ 지 급 일 : 2024. 12월 중\n※ 지원대상 예산범위 내 신규지원자 우선 지원하며, 연장 신청자 초과 접수될\n경우 가점배점표를 통해 지원결정"
700,"▢ 세부내용\n - 신혼부부 : 대출 잔액의 연 2%이내 (최대 300만원 / 매년) ＊ 신혼부부의 경우 소득수준 및 자녀 수에 따라 차등지급\n - 청 년 : 대출 잔액의 연 2%이내 (최대 100만원 / 매년)\n ※ 초과 접수될 경우, 가점배점표를 통해 지원결정\n▢ 지원횟수 : 연 1회, 가구 당 최대 3년 지원\n ※ 신규지원자 우선 선정 후 연장지원자 선정되므로, 기 지원가구도 매년 신청하여 선정되어야 지원가능. ▢ 지급방식 : 신청인의 명의 계좌 입금\n▢ 선정통보 : 2024. 12월",NaN
813,"2023. 10.~2024. 9. 기간 동안 실제 납부한 주택 전월세자금 대출이자 지원 (대출잔액의 2%, 최대 200만원까지)",NaN
893,"1. 지원금액 : 금융권에서 대출받은 주택 전세자금의 매월 대출 잔액의 연2%를 연간 최대 2백만원까지 지원(천원 미만 절사)\n2. 지원내용 : 2023년 7월 ~ 2024년 6월 기간 동안 납부한 이자\n (기 납부한 이자가 12개월 미만인 경우에도 지원)\n3. 우대지원 : 유자녀가구(1인당), 장애인, 다문화가구에 대하여 본인이 지출한 이자 범위내에서 매월 대출잔액의 연0.2% 가산지원(대상자 중복 가산 불가)\n - 지원금과 가산금을 합하여 연 최대 200만원까지 지원\n4. 대출기간이 1년 미만인 경우 최대 지원 가능한 금액 산정\n (연 최대 200만원÷12개월×대출금 상환한 개월 수)\n5. 지급방식 : 신청인 계좌 입금\n6. 지 급 일 : 2024. 11월 중 (선정자 개별 안내)\n ※ 지급일은 상기 일정에 따라 변동될 수 있음.",선정자 9월 중 개별(문자) 통지
894,"❍ 지원내용 : 대출금 1억 5천만원 범위에서\n - 신혼부부 : 대출금의 전세 2.5% 이내, 월세 2.7% 이내 (최대 125 ~ 135만 원)\n - 청 년 : 대출금의 전세 1.2% 이내, 월세 1.4% 이내 (최대 60 ~ 70만 원)\n❍ 지원횟수 : 연 1회, 가구 당 최대 3년\n※ 기지원가구도 매년 신청하여 선정되어야 지원 가능",❍ 지 급 일 : 2024. 10월 말
995,"신혼부부 가구 전·월세 대출금 이자 상환액 지원(최대 연 3.0%)\n ⇨ 대출잔액 1억 원 한도 내, 대출이자 납부 범위 내 지원\n\n- 지원기간 : 최대 2년\n- 지급방법 : 연 1회 지급 * 기 납부한, 상환이자 정산지원","□ 선정기준 : 부부합산 연소득, 자녀 수 배점기준에 따라 대상자 선정"
1048,"지원내용 : 동두천시에 주소를 두고 있는 신혼부부, 청년에게 1회 1백만원 한도, 전세대출 원금의 1~1.5% 이내 금액을 현금으로 지급",NaN
1121,□ 지원내용 \n○ 지원내용: 주택구입 대출잔액(5천만원 한도)의 3% 이내 지원(반기 별 최대 75만원) \n○ 지원금액: 2024년 1월 ~ 2024년 6월까지 납부한 이자 금액(최대 75만원)\n○ 지급방법: 지원대상자 계좌입금,□ 향후일정(일정 변경 가능성 있음)\n- 지원 대상자 선정: 2024. 10. 25.(금) 예정(개별통보)\n- 지원금 지급일: 2024. 11. 22.(금) 예정\n※ 대상자 심사 지연 등으로 일정이 변경될 시 신청자에 별도 통보
1200,"ㅁ 지원금액 : 전세자금 대출 잔액의 1.5% (최대 130만원) \nㅁ 지원횟수 : 연 1회, 최대 5년간 지원(기 지원 가구도 매년 신규신청)\nㅁ 대상주택: 안산시 소재 전용면적 85㎡ 전세전환가액 3억원 이하 주택 \n※ 기타 자세한 사항은 공고문 확인 필수",NaN
1201,"○ 지원내용: 2023년 1월~2023년 12월 기간 동안 실제 납부한 이자(납부기간이 12개월 미만인 경우에도 지원)\n○ 지원금액: 금융권에서 대출받은 주택전월세자금 중 실제 상환한 이자를 지원,대출잔액의 2% 이내 및 연간 최대 2백만원 이내 지원(천원 미만 절사)\n○ 지원기간: 연 1회, 최대 2년간 지원\n ※ 기 지원가구도 매년 신규 신청하여야 함\n○ 우대지원: 유자녀 가구, 장애인 가구, 다문화 가족 0.2% 가산(금액 한도는 동일)",NaN
1220,"○ 사업내용 : 구입·전월세 목적으로 금융권 대출을 실행한 청년 및 신혼부부에 가구당 최대 100만 원 한도의 대출이자 지원\n\n○ 지원횟수 : 가구당 최대 2회 지원 (매년 1회 신청·접수, 회차당 50만 원까지 지원)",NaN
1258,"신혼부부 : 연 최대 150만원(대출금 1억 5000만원이내, 대출금의 1% ) 최장 3년 까지\n- 청년 : 연 최대 100만원 (대출금 1억원 이내, 대출금의 1% ) 최장 3년 까지",NaN
1282,"□ 지원내용: 전월세 보증금 대출잔액의 2%, 가구당 최대 300만원\n ※ 임대차계약기간 내 금융기관 서류의 대출실행 유지 기간(월/당해 연도) 일시금 지급\n 예) 임대차계약기간 및 대출기간: 2024년 2월 1일 ~ 2026년 2월 1일\n · 2024년도 대출이자 지원사업 신청 – 11개월분 지원",NaN
1368,"- 지원내용: 주택 전세자금 대출잔액의 1.5%, 최대 130만원\n ※ 연1회(최대 5년) 지원, 기 신청 가구도 매년 신규 신청",NaN
1644,"□ 사업명: 「2024년 구리시 무주택 신혼부부 전월세자금 대출이자 지원」\n□ 잔여예산: 33,530천원\n□ 지원내용: 주택 전월세자금 대출잔액의 1%, 가구당 최대 100만원\n\n※ 보다 상세한 내용은 공고문을 확인해주세요.",NaN
1710,□ 지원내용 : 무주택 신혼부부 주택 전세자금 대출이자 지원\n가. 주택 전세자금 대출잔액의 1.5%에 해당하는 이자액을 최대 100만원 지원\n※ 천원단위 이하 절사\n나. 지원횟수는 연 1회로 한정 (최대 2년간 지원)\n다. 신청자가 많을 경우 다음의 우선순위에 따라 지원\n※ 우선순위\n- 1순위 : 혼인신고일이 먼저인 신혼부부\n- 2순위 : 자녀수가 많은 가구\n- 3순위 : 기준중위소득이 적은 신혼부부,공고문 참고
1813,"□ 지원내용 및 지원기준\n가. 지원횟수는 연 1회로, 매년 신규 신청 접수(요건 충족 시 최장 7년간 지원)\n나. 주택전세자금 대출잔액의 1.5%(금리기준)내에서 지급하되, 최대 100만원 지원(*천원미만 절사)\n※ (예시1) 대출금리(금융권 발행 서류 발급일 기준 금리) 1.5% 미만인 경우\n→ 대출잔액 6000만원, 금리 1.2% : 6000만원 × 1.2% = 72만원 \n(예시2) 대출금리(금융권 발행 서류 발급일 기준 금리) 1.5% 초과인 경우\n→ 대출잔액 8000만원, 금리 3% : 8000만원 × 1.5%(한도) = 120만원(100만원 지급)","□ 지원절차 : 접수(읍·면·동 ) ⇨ 대상자 결정(시) ⇨ 지급(시)\n\n□ 지급일 : 2024. 9. 4.(수) (일정은 변경될 수 있으며, 대상자 결정 결과는 개별문자 통보)\n\n□ 선정방법\n 가. 2024. 01. 02. 기준 우선순위에 따른 순서대로 선정\n - 1순위 : 자녀수가 많은 가구 (만 18세 이하의 자녀, 2005.01.03. 이후 출생)\n - 2순위 : 장애인 포함 가정 (등록 장애 가구원 유무)\n - 3순위 : 혼인기간 오래된 순 (연도 기준)\n - 4순위 : 김해시 연속 거주기간 오래된 순 (기준일로부터 현 거주기간 역산)"
1843,□ 지원내용 : 무주택 신혼부부 주택 전세자금 대출이자 지원\n가. 주택 전세자금 대출잔액의 1.5%에 해당하는 이자액을 최대 100만원 지원\n※ 천원단위 이하 절사\n나. 지원횟수는 연 1회로 한정 (최대 2년간 지원)\n다. 신청자가 많을 경우 다음의 우선순위에 따라 지원\n※ 우선순위\n- 1순위 : 혼인신고일이 먼저인 신혼부부\n- 2순위 : 자녀수가 많은 가구\n- 3순위 : 기준중위소득이 적은 신혼부부,-
1849,"□ 지원내용\n- 신혼부부의 주택 매입·전세자금 대출이자 최대 2% 지원\n- 대출금 최대 2억 한도, 이자 최대 400만원/년 ※ 매입·전세 최대 4년 지원",-
1880,"□ 지원내용 : 주택구입 대출잔액(5천만원한도)의 이자지원(3%이내) \n□ 지원금액 : 2023. 7월 ~ 2024. 6월까지 납부한 이자금액(최대 150만원) \n- 2023. 7월 ~ 12월까지 납부한 이자금액(최대 75만원)\n- 2024. 1월 ~ 6월까지 납부한 이자금액(최대 75만원)\n□ 지원기간 : 매년 신규신청 접수,연 1회(상·하반기 포함 요건 충족 시 최장 5년간 지원) \n□ 지급방법 : 대상자 계좌입금\n□ 지급일 : 2024. 8월限 (일정은 변경될 수 있으며, 대상자 선정 결과는 개별문자 통보)",□ 선정방법 : 자격요건 충족 신청자\n※ 지원금액 초과 시 우선순위 배점표에 따라 고배점순으로 선정\n※ 동점자일 경우 우선순위\n1. 자녀수가 많은 가구\n2. 부부합산 연소득이 낮은 가구
1882,□ 지원내용 : 주택구입 대출잔액(5천만원한도)의 이자지원(3%이내)\n□ 지원금액\n- (상반기 지원) 2023. 7월~12월까지 납부한 이자금액(최대 75만원)\n- (하반기 지원) 2024. 1월~6월까지 납부한 이자금액(최대 75만원)\n□ 지원기간 : 2024년 상·하반기 신규신청 접수(요건 충족 시 최장 5년간 지원)\n□ 지급방법 : 사업대상자 계좌입금,□ 대상자 선정\n○ 선정방법 : 자격요건 충족 신청자\n※ 지원 금액 초과 시 우선순위 배점표에 따라 고배점순으로 선정\n※ 동점자일 경우 우선순위\n1. 자녀수가 많은 가구\n2. 부부합산 연소득이 낮은 가구
1915,"□ 지원내용 : 전월세 대출금 최대 2년간 연3.0%이내 이자상환 지원\n* 대출잔액 1억원 한도내, 대출이자 납부 범위 내\n□ 지원지급방법 : 연 1회 지급\n* 공고일 기준 이전 1년간 실제 납입한 대출이자 상환액에 대하여 정산 지원",-
2129,"□ 지원내용\n- 전세자금 대출잔액의 1.5% 이내 최대 100만원 지원\n- 자녀가 있는 경우 1인당 0.5%를 가산하고, 최대 150만원 지원\n - 연 1회 지원(매년 신청 접수해야 하며 요건 충족 시 최대 3년간 지원)\n□ 지급방법 : 지원대상자 계좌입금","□ 신청 결과 알림: 신청인에게 개별 문자 알림\n□ 지원금 지급: 2024년 8월부터 순차적으로 지급(※내부 사정에 따라 변동 가능)\n□ 대상자 선정\n○ 선정방법 : 모든 자격요건 충족 시 지원대상자로 선정\n○ 예산 소진 시까지 선착순에 의해 선정하며, 동시 신청자가 많을 경우 다음의 우선순위를 적용\n※우선순위 공고문 참고"
2147,□ 지원내용 : 주택구입 대출잔액(5천만원 한도)의 이자지원(3%이내)\n- 요건충족 시 최대 5년 지원(기지원 가구도 반기마다 신규신청 필요) \n□ 지원금액 : 2023. 7월 ~ 12월까지 납부한 이자금액(최대 75만원 지원)\n□ 지급방법 : 지원대상자 계좌입금 ※ 일정은 변경될 수 있음,□ 선정발표 : 2024. 6. 18.(화) [개별문자 통보]\n□ 지 급 일 : 2024. 6. 21.(금)
2167,"□ 지원내용 : 청년 및 신혼부부 주거자금(전세, 주택구입) 대출 이자 지원\n○ 주거자금(대출잔액 기준)의 대출이율 1.5%(최대 1백만원 한도) 지원\n○ 신청일 기준 연 1회 지원, 지원기준 해당 시 최장 3년 간 지원 가능\n※ (예시) 청년자격으로 신청하여 1회를 지원받고, 혼인 이후 신혼부부 자격으로 신청 시 추가 2회 지급 가능\n\n□ 지급시기 : 신청서 및 제출서류 검토 후 1개월 내 지급",공고문 참고
2348,"○ 지원내용\n - 전세보증금 대출잔액의 1%(월세보증금 1.5%)이내 대출이자 지원\n - 최대 3년간 지원(연 1회, 최대 100만원 지원)\n○ 지급방법 : 신청인(배우자) 지정계좌로 지급(2024. 6. 30.)\n * 지급일은 사정에 따라 일부 변동될 수 있음.",NaN
2388,○지원내용 : 전세자금 대출 잔액의 1% 범위 내 이자 지원(최대 100만원),NaN
2404,"□ 지원내용 : 주택구입 대출잔액(5천만원 한도)의 이자지원(3% 이내)\n□ 지원금액 : 2023. 7월~12월까지 납부한 이자금액(최대 75만원)\n□ 지원기간 : 매년 상·하반기 신규 신청 접수, 연 2회(요건 충족시 최장 5년간 지원)\n□ 지급방법 : 지원 대상자 계좌입금",□ 신청 결과 알림 : 신청인에게 개별 문자 알림\n□ 지원금 지급: 2024년 6월 중(※내부 사정에 따라 변동 가능)
2517,□ 주택전세자금 대출이자 100만원 이내\n ※ 3년간 지원,□ 군 신속허가과
2557,"○ 지원내용: 주택 전월세자금 대출잔액의 1%, 가구당 최대 100만원\n○ 사업량: 60,000천원\n\n▶ 자세한 사항은 첨부된 선발계획 공고문 참고",NaN
2632,"○지원내용\n -주택 전세자금 대출잔액의 1%, 연 1회, 최대100만원 (천원 미만 절사)\n -신혼부부 해당 기간 내 최대 5년간 지원 (이전 신청 세대도 신규 신청 필요)","○ 선정결과 통보 : 2024. 6월 중 개별 통보(문자) 예정 /지 급 일 : 2024. 6월중 (신청인 계좌로 입금)\n ※ 상기 일정은 사정에 따라 변경될 수 있음\n○ 지원 대상자 선정 기준\n -적합자에 대한 지원금액이 예산을 초과할 경우 아래 배점표상 최다득점자 순으로 예산 범위 내 지원하며, 동점자가 있는 경우 평가항목별 점수가 ①→②→③순으로 높은 신청자에게 선순위 부여"
2670,"○ 지원내용\n- 주택 매입·전세 자금 대출 잔액의 1%, 연 1회, 최대 100만원(천원 미만 절사)\n- 신혼부부 해당 기간 내 최대 2회 지원\n○ 대상주택 : 안양시 소재 주택 (단독, 다가구, 다세대, 연립주택, 아파트, 주거용 오피스텔 등)",NaN
2822,대출이자 금액 지원(최대 75만원까지 지원)\n※실제 이자를 납부한 금액이 최대 지원액(75만원) 이하일 경우 실납입금액만 지원합니다.,-
2825,"□ 지원금액 : 주택구입 대출잔액(5천만원 한도)의 3% 지원(연 최대 150만원)\n\n□ 지원기간 : 요건 충족시 최장 5년간 지원(매 반기 신규신청 접수, 연 2회)\n- 전연도 하반기(7~12월)분 이자 : 당해연도 상반기 모집 및 지급(최대 75만원)\n- 당해연도 상반기(1~6월)분 이자 : 당해연도 하반기 모집 및 지급(최대 75만원)\n※사업비 소진 후 사업종료",-
2827,- 2023. 7. 1.부터 2023. 12. 31.까지 납부한 대출이자 합산 금액 지원(최대 75만원까지 지원)\n- 변동금리일 경우 해당기간 평균 이율을 산출하여 3%이내 분 지급\n- 실제 이자를 납부한 금액이 최대지원액 이하일 경우 납부액만 지원 \n- 1가구당 최대금액 75만원 한도 지급,- 상반기 선정자 발표일: 5월 17일(금) 예정 (개별 통보) ※ 일정 변경 가능성 있음\n- 상반기 선정자 지원금 지급: 6월 14일(금) 예정 ※ 일정 변경 가능성 있음
3070,"○ 지원내용 : 대출금 1억 5천만원 범위에서\n - 신혼부부 : 대출금의 전세 1.3% 이내, 월세 1.5% 이내 (최대 65 ~ 75만 원)\n - 청 년 : 대출금의 전세 0.6% 이내, 월세 0.8% 이내 (최대 30 ~ 40만원)\n\n○ 지원횟수 : 연 1회, 가구 당 최대 3년 \n ※ 기지원가구도 매년 신청하여 선정되어야 지원가능",NaN
3103,"□ 지원금액 : 납입한 대출이자의 일부지원\n(자녀수별 차등 지원)* 무자녀 0.5%, 1자녀 0.7%, 2자녀 이상 1.0% \n□ 지원한도 : 대출(신청)자가 은행에 납입한 총 이자액 범위 내\n□ 지원기간 : 본인 대출기한 내 대출일로부터 최장 6년 (단, 2자녀이상일 경우 최장8년)\n□ 지급방법 : 연간 2회(상,하반기) 청구 및 지급\n□ 취급은행 : 농협은행, 우리은행, 국민은행, 신한은행, IBK기업은행",□ 상반기(1차)\n지원대상 접수기간 : 2024. 1. 1. ~ 4. 30.\n대출이자 청구기간 : 2024. 5. 1. ~ 5. 15.\n대출이자 지원기간 : 2023. 11월 ~ 2024. 4월(6개월)\n지급일 : 2024. 6월중\n\n□ 하반기(2차)\n지원대상 접수기간 : 2024. 4. 1. ~ 10. 31.\n대출이자 청구기간 : 2024. 11. 1. ~ 11. 15.\n대출이자 지원기간 : 2024. 5월 ~ 2024. 10월(6개월)\n지급일 : 2024. 12월중
3127,"□ 지원내용 : 전세자금 대출금액(잔액)의 2%(최대 100만원/연)\n□ 지원한도 : 연 1회, 자격 및 지원기준 충족 시 최대 2년까지 지원\n□ 지급방법 : 신청자 개인계좌 입금",□ 지급절차\n - 자격 확인 : 신청일로부터 1주 이내\n - 대상자 최종 결정 : 서류 접수완료 후 3주 이내\n - 지원금 지급 : 대상자 최종결정 후 2주 이내\n□ 결과통보 : 개별 문자통보
3283,"주택 전월세보증금 대출 잔액의 1.0~1.5% 지원 (연 1회, 최대 100만원)",자격 심사 후 3월중 발표 및 지급

In [118]:
# 컬럼 안의 텍스트를 줄임 없이 출력
pd.set_option('display.max_colwidth', None)

# 예시: 청년 대상 대출이자 정책의 정책지원내용 전체 출력
df_loan_bubu_with_interest[['추가신청자격조건내용']]

                                                                                                                                                                                                                                                                                                                                추가신청자격조건내용
35                                                                                                                                                                                                                                                                                                           도내 혼인신고일로부터 7년 이내 신혼부부 중 무주택자
212                                                                                                                                                                                                                                                                          주택도시기금 신혼부부 전용 전세자금 대출 대상자만 지원 가능\n예비부부도 지원 가능(3개월 이내 결혼 예정자)
225                                                                                                                                                                                                                                                                                                                                    NaN
346                                                                                                                                                                                                                                                                                                                                    NaN
401                                                                                                                                                                      (연 령) 부부 모두 순천시에 주소를 둔 만18세~45세 무주택 신혼부부(혼인신고\n              5년 이내)\n    (소 득) 부부합산 연소득 7,500만원 이하(외벌이 5,000만원 이하)\n    (주 택) 순천시 소재 주택, 전세가격 3억원 이하, 전용면적 85㎡ 이하
549                                                                                                                                                                                                                                                                                                                                    NaN
554                                                                                                                                                                                                                                                                                                                   부부 중 1명이 18 ~ 39세 이하
591                                                                                                                                                                                                                                                                                                                                    NaN
690                                                                                                                                                                                                                                                                                                                                    NaN
700                                                                                                                                                                                                                                                                                                                                    NaN
813                                                                                                                                                                                                                                                                                                                                    NaN
893   □ 지원 대상 주택\n1. 임차주택 : 여주시 소재 단독, 다가구, 다세대, 연립주택, 아파트, 오피스텔(주거용도만)\n    ※ 다중주택, 옥탑층 등 건축물대장상 주택이 아닌 곳은 불가\n2. 임차금액 : 3억원 이하\n\n참여 제한 대상: \n1. 기초생활보장수급자 (생계.의료.주거급여 수급자)\n2. 공공임대 (국민임대주택, 영구임대주택, LH매입임대주택, LH전세임대주택)거주자\n3. 기타 공공기관 주택 대출 등 관련 유사사업 지원 대상자\n    ※ 주택도시기금,  주택금융공사 대출은 가능)\n4. 신청인(또는 배우자) 부부의 직계존비속인 자와 임차계약을 체결한 자
894                                                                                                                                                                                                                                                                                                                                    NaN
995                                                                                                                                                                                                                                                                                                                                    NaN
1048                                                                                                                                                                                                                                                                                                                                   NaN
1121                                                                                                                                                                                                                                                                                                                                공고문 참고
1200                                                                                                                                                                                                                                                                                                                                   NaN
1201                                                                                                                                                                                                                                                                                                                                   NaN
1220                                                                                                                                                                                                                                                                                                                                   NaN
1258                                                                                                                                                                                                                                                                                                                                   NaN
1282                                                                                                                                                                                                                                                                                                                                   NaN
1368                                                                                                                                                                                                                                                                                                                                   NaN
1644                                                                                                                                                                                                                                                                                                                                   NaN
1710                                                                                                                                                                                                                                                                                                                                공고문 참고
1813                                                                                                                                                                                                                                                                                                                                공고문 참고
1843                                                                                                                                                                                                                                                                                                                                     -
1849                                                                                                                                                                                                                                                                                                                                     -
1880                                                                                                                                                                                                                                                                                                                                공고문 참고
1882                                                                                                                                                                                                                                                                                                                                공고문 참고
1915                                                                                                                                                                                                                                                                                                                                     -
2129                                                                                                                                                                                                                                                                                                                                공고문 참고
2147                                                                                                                                                                                                                                                                                                                                공고문 참고
2167                                                                                                                                                                                                                                                                                                                                공고문 참고
2348                                                                                                                                                                                                                                                                                                                                   NaN
2388                                                                                                                                                                                                                                                                                                                                   NaN
2404                                                                                                                                                                                                                                                                                                                                공고문 참고
2517                                                                                                                                                                                                                                                                                                                                   NaN
2557                                                                                                                                                                                                                                                                                                                                   NaN
2632                                                                                                                                                                                                                                                                                                                                   NaN
2670                                                                                                                                                                                                                                                                                                                                   NaN
2822                   허위·부정한 방법 등으로 지원금을 받은 경우 지원금 환수조치 및 향후 신혼부부 주택구입 대출이자 등 지원사업 신청에서 제한될 수 있습니다.\n지원 대상자로 선정된 후에도 제외대상으로 확인 시 선정 취소됩니다.\n제출된 모든 서류는 반환하지 않으며, 기재내용 및 제출서류가 사실과 다른 경우 지원 대상자로 선정되었다 하더라도 취소될 수 있습니다.\n제출서류가 미흡한 경우 별도 자료를 요청할 수 있으며, 심사가 지연될 수 있으므로 주의 바랍니다.\n기재사항 착오 및 누락, 허위 기재, 연락불능 등으로 인해 발생하는 불이익은 신청자의 책임으로 합니다.
2825                                                                                                                                                                                                                                                                                                                                     -
2827                                                                                                                                                                                   - 지원기준 충족 가구 신청자가 지원 물량 초과 시 우선배점표에 따라 '혼인기간(10~30점), 부부합산연소득(15~40점), 자녀수(15~30점)' 배점 후 대상자 선정\n- 동점자일 경우 우선순위: 1. 자녀 수가 많은 가구 2. 부부 합산 연소득이 낮은 가구
3070                                                                                                                                                                                                                                                                                                                                   NaN
3103                                                                                                                                                                                       □ 지원대상 : 『주택도시기금 신혼부부 전용 전세자금대출』신규 대출자 및 대출 연장자('21.1월 이후)\nㅇ 대출(신청)자의 주민등록 및 임차(전세)주택 주소지가 광주지역에 소재\nㅇ 3개월이내 혼인 예정이거나 혼인신고일 기준 7년차 이내 무주택 신혼부부
3127                                                                                                                                                                                                                                                                                                                                     -
3283                                                                                                                                                                                                                                                                                                                                   NaN

In [173]:
# 지원기준이 명확히 나와있는 정책이 없고 다 홈페이지참조라서 추천을 어떻게해야할지...

In [115]:
# 청년 대상 정책 조회수 통계
youth_views = df_loan_youth['조회수'].astype(float)
print("청년 대상 정책")
print("정책 수:", len(youth_views))
print("평균 조회수:", youth_views.mean())

청년 대상 정책
정책 수: 19
평균 조회수: 43.8421052631579

In [117]:
# 신혼부부혼부부 대상 정책 조회수 통계
youth_views = df_loan_bubu['조회수'].astype(float)
print("청년 대상 정책")
print("정책 수:", len(youth_views))
print("평균 조회수:", youth_views.mean())

청년 대상 정책
정책 수: 51
평균 조회수: 44.294117647058826

In [121]:
# 전월세의 기준 금전기준 or 주택지원
# 컬럼 안의 텍스트를 줄임 없이 출력
pd.set_option('display.max_colwidth', None)


df_rent[['정책지원내용']]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                정책지원내용
19                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          옛 외국인유학생기숙사 누리관을 리모델링하여 대전소재 사업장에서 근무하는 청년 근로자 대상 기숙사 조성 및 운영\n\n□ 위치 : 대전 유성구 엑스포로 97번길 103(도룡동)\n□ 규모 : 지상 1층 ~ 10층, 연면적 7,043㎡, 1실 18.41㎡\n□ 시설 : 공유라운지 등 공유공간 11개소\n□ 입주기간 : 2년\n※ 입주 기간 만기시 연장은 1년씩 최대 2회 가능 (입주 대기자가 없는 경우에 가능)\n□ 입주부담금\n  ○ 보증금 : 1,000,000원\n  ○ 임대료 : 250,000원\n  ○ 관리비 : 20,000원(인터넷 및 보안 등 이용료)\n  ○ 공과금  : 별도(전기, 가스, 수도 등)\n  ○ 정기주차권 : 10,000원 / 정기주차권은 주차 희망자에 한함. 입주민외 차량의 경우 정기주차권 발급불가\n□ 배치가구 : 침대, 냉장고, 옷장, 책상, 의자, 신발장, 시스템에어컨, IP-TV, WIFI\n※ 객실 난방방식은 천장형 에어컨 이용 방식임 (바닥에 별도 난방없음)
113                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           사업장 임대료 월 20만원 지원 (최대 4개월, 총 80만원) / 30명
125                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ㅇ (사업 근거)\n   - 「민간임대주택에 관한 특별법」\n   - 「서울특별시 청년안심주택 공급 지원에 관한 조례」\n ㅇ (추진 경과)\n   - ’16.03.25.  역세권 청년주택 공급계획 수립\n   - ‘16.07.14. 「역세권 청년주택 공급 지원에 관한 조례」제정·시행\n   - ‘16.08.22. 「역세권 청년주택 건립 및 운영기준」수립·시행\n   - ‘19.11.26.  청년·신혼부부 주거비 지원계획 수립\n   - `21.09.29. 「역세권 청년주택 건립 및 운영기준」개정(10차)\n   - ’23.03.06.  역세권청년주택 혁신을 통한 ‘청년안심주택 추진방안’ 수립\n   - ’23.05.22. 「청년안심주택 공급 지원에 관한 조례」개정\n   - ’23.07, ’24.08. 「청년안심주택 건립 및 운영기준」개정(11차, 12차)\n   - ’24.12.27. 「서울특별시 모두의 안심주택 건립 및 운영기준」제정\n ㅇ (사업 기간)\n   - 2016년 7월 ~ 2025년 12월\n ㅇ (사업 대상) \n   - 지원대상 : 청년 및 신혼부부\n   - 연령기준 : 19~39세\n   - 소득기준 : 도시근로자 월평균소득 100% ~120% 이하\n  ㅇ (사업 내용)  \n   - 역세권(간선도로변)에 민간이 임대주택을 건설하게 하고 일부를 청년안심주택(공공임대)으로 매입하여 청년ㆍ신혼부부에게 공급하는 사업\n ㅇ (사업비)  79,662백만원 (국비 66,350 / 시비 13,312)
127                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ㅇ 사업 근거\n   - 서울시 사회적 가족도시 구현을 위한 1인가구 지원 기본조례 제11조\nㅇ 추진 경과\n   - 전월세 안심계약 도움서비스 추진계획 수립\t: ’22. 1월\n   - 5개 자치구 서비스 시범 운영\t \t\t  \t: ’22. 3월\n   - 25개 전 자치구로 서비스 확대\t\t\t: ’23. 5월\n   - 10개 자치구 토요일 운영\t\t\t\t: ’24. 4월\nㅇ 사업 기간 : ‘22. 3 ~ 계속\nㅇ 사업 대상 : 서울시 거주 또는 거주예정 1인가구(독립가구 예정자 포함)\nㅇ 사업 내용 : 자치구별 주거안심매니저가 주거정책 안내, 주거지 탐색, 집보기 및 계약시 동행지원\nㅇ 사 업 비  : 380백만원
128                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ㅇ (사업 근거)\n   -「주거기본법」제15조(주거비 보조), 「청년기본법」제20조(청년 주거지원)\n   -「서울특별시 청년주거 기본 조례」제7조(청년주거사업),「서울특별시 청년 기본 조례」제13조(청년의 주거안정 등)\n ㅇ (추진 경과)\n   - 청년자율예산제에 따른 청년층 신규사업으로 요구(’19.9.)\n   - ’20년도「청년 월세 지원」사업 모집(’20.6.)\n   - ’21년도「청년 월세 지원」사업 모집(’21.3./’21.7.)\n   - ’22년도「청년 월세 지원」사업 모집(’22.6.)\n   - ’23년도「청년 월세 지원」사업 모집(’23.5./’23.9.)\n   - ’24년도「청년 월세 지원」사업 모집(’24.4.)\n ㅇ (사업 기간) ’25.1.1.~’25.12.31.(연례반복)\n ㅇ (사업 대상) 서울시 월세 거주 무주택 청년 1인 가구\n   - (연령 기준) 19~39세\n   - (소득 기준) 건강보험료 납입 기준 중위소득 150% 이하\n   - (재산 기준) 일반재산 1억 3천만원 이하, 자동차 2,500만원 미만\n   - (기타 조건) 임차보증금 8천만원 이하 및 월세 60만원 이하 \n ㅇ (사업 내용) 월 임차료 지원(20만원×12개월)   ※ 생애 1회 \n ㅇ (사 업 비) 45,817백만원
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ...
3391                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               생애 1회, 이사비 최대 20만원 실비 지원 \n※ 이사비 및 중개 보수비에 실제 소요된 비용만 지원하며, 청소비는 제외
3393  □ 전세보증금 지원한도액 및 지원가능 주택면적\n(단독형 1인) 수도권 1.2억원 / 광역시 9,500만원 / 기타 도 지역 8,500만원\n(쉐어형 2인)  수도권 1.5억원 / 광역시 1.2억원 / 기타 도 지역 1억원\n(쉐어형 3인 이상) 수도권 2억원 / 광역시 1.5억원 / 기타 도 지역 1.2억원\n※ 셰어형을 원하는 경우 단독형으로 신청, 입주대상자 선정 안내를 받은 후 해당 지역본부에 연락하여 셰어형으로으로 요청(셰어형은 동성만 지원가능. 단, 남매는 허용) \n※ 호당 전용면적 85㎡ 이하여야 하며, 가구원이 5인 이상인 경우(셰어형에 한함) 전용면적 85㎡를 초과한 주택 지원가능\n※ 지역별 지원한도액을 초과하는 주택은 임차권을 LH에게 귀속하고 호당 지원한도액을 초과하는 금액을 입주대상자가 부담하는 조건으로, \n1호에 1인 입주 시 호당 지원한도액의 150%이내, 2인 이상 입주 시(셰어형에 한함) 지원한도액의 200% 이내만 지원가능\n\n□ 지원가능주택\nㅇ 당첨자가 신청한 지역의 전용면적 85㎡ 이하 전세 또는 보증부월세로 계약 가능한 주택 (단독, 다가구, 다세대, 연립주택, 아파트, 주거용 오피스텔) \nㅇ 부채비율(전세지원금 포함 총부채/주택가격)이 90% 이하인 주택\nㅇ 주거용 오피스텔의 경우 바닥난방이 되며, 별도로 취사 · 세면시설 및 화장실을 갖추어 주거용(사실상 사용)으로 이용가능하여야 함\nㅇ 보증부월세 전세임대주택의 경우 매월 지급하는 월세는 입주대상자가 직접 임대인에게 지급하여야 하며, 1년치 월세에 해당하는 금액을 계약시 기본보증금 외에 추가부담(전세계약 만료시 반환함)하여야함\n[단, 수도권(60만원), 광역시(45만원), 기타지역(40만원) 한도의 보증부월세는 입주대상자가 원할 경우 3개월치 월세에 해당하는 금액만 입주자가 부담하고 9개월치 월세는 임차료 지급보증으로 대체가능\n\n□ 임대조건\nㅇ 임대보증금 : 100만원\nㅇ 월임대료 \n - 22세 이하 무이자\n - 전세임대주택 거주 5년 이내 50%감면 (단, 다른 우대금리와 중복적용 불가)\n - 전세임대주택 거주 5년 이후 보증금 지원 규모별 연 1.0~2.0%\nㅇ 우대금리 적용 \n - 청년 1순위 : 0.5%p (단, 다른 우대금리와 중복적용 불가) \n - 1자녀 0.2%P, 2자녀 0.3%P, 3자녀이상 0.5%P (단, 최저금리는 1.0%) \n - 생계 · 의료급여 수급자 0.2%P (단, 최저금리는 1.0%) \n ※ 월 임대료 및 우대금리 등은 주택도시기금 운용계획 융자조건에 따라 변경 가능\n ※ 주거급여 수급세대의 경우 지자체에서 신청자 계좌로 지급되던 주거급여액이 LH 계좌로 지급되며,  해당금액은 월 임대료로 자동 수납처리됨\n * 주거급여법 제7조제4항에 의거 공사가 직접 수납하며 보증부월세 계약은 제외\n\n□ 임대기간: 2년\n ㅇ 최초 임대기간 경과 후 2년 단위로 최대 14회 재계약 가능하나, 4회를 초과하여 재계약을 체결할 때에는 무주택세대구성원으로서 아래 재계약 기준을 충족하여야 함\n□ 재계약기준\n ㅇ (4회를 초과하여 재계약 체결 시) 무주택세대구성원으로서 소득기준 및 자산기준(전년도 도시근로자 가구원수별 가구당 월평균소득의 105% 이하, 영구임대주택 자산기준*)을 \n충족하여야 하며, 미 충족 시 1회에 한해 재계약 체결 가능하나 임대보증금 및 임대료가 80% 할증
3421                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             □ 기본조건\n ㅇ 지원기간 : 2024. 2. ~ 10.(최대 6개월)\n ㅇ 지원금액 : 최대 300만원(최대 월 50만원씩 6개월 지원)\n  ※ 실제 월 임차료 내 최대 50만원 까지 지원\n  ※ 보증금, 관리비 등은 지원 불가\n ㅇ 지급방법 : 보조금 최종 선정 후 6개월분 일괄지급\n\n    (기타사항) 아래 결격사유에 해당하지 않는 자\n    - 정부, 지자체 등이 지원하여 조성·운영 중인 공간을 임대한 경우(BI, 1인 창조기업 비즈니스센터 등)\n    - 창업 아이템 개발·생산을 위한 공간의 임대가 아닌, 거주 형태 공간을 임대한 경우\n    - 임차인과 임대인의 관계가 직계존·비속 및 특수관계인 인 경우
3427                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             □ 대출금리 : 연1.5% ~ 2.7%\n\n□  대출한도: 다음 중 작은 금액으로 산정 \n ○ 호당대출한도 : 수도권(서울/경기/인천) 3억원, 수도권 외 2억원\n ○ 소요자금에 대한 대출 비율\n  - 신규계약 : 전세금액의 80퍼센트이내\n  - 갱신계약 : 증액금액 이내에서 증액 후 총 보증금의 80퍼센트이내\n ○ 담보별 대출한도\n  - 한국주택금융공자 전세대출보증 : 해당 보증 규정에 따름\n  - 주택도시보증공사 전세안심대출보증 : 해당 보증 규정에 따름\n  - 채권양도협약기관 반환채권양도 : 연간인정소득 - 본인 부채금의 25% - 기 기금전세자금대출잔액\n\n□ 이용기간: 2년(4회 연장하여 최장 10년 가능)\n○ 주택도시보증공사 전세금안심대출 보증서 : 최대 2년 1개월(4회 연장하여 최장 10년 5개월 가능)\n○ 최장 10년 이용 후 연장시점 기준 미성년 1자녀당 2년 추가(최장 20년 이용 가능)

In [135]:
def classify_rent_support(row):
    text = (str(row['정책지원내용']) + ' ' + str(row['정책명'])).lower()

    if any(keyword in text for keyword in ['보증금', '월세', '대출', '이자', '지원금', '한도', '이차보전','임대료']):
        return '금전 지원'
    elif any(keyword in text for keyword in ['기숙사', '임대주택', '공공임대', '전세임대', '매입임대', '입주','주택 공급']):
        return '주택 제공'
    else:
        return '기타'

In [138]:
df_rent['지원형태'] = df_rent.apply(classify_rent_support, axis=1)


# 결과 확인
df_rent['지원형태'].value_counts()

# 금전을 원하는지 주택을 원하는지 사용자에게 확인 필요

지원형태
금전 지원    150
주택 제공     34
기타        11
Name: count, dtype: int64

In [137]:
# 기타 내용은 뭐지
df_rent_etc = df_rent[df_rent['지원형태'] == '기타']
df_rent_etc[['정책명', '정책지원내용']].head(10)  # 상위 10개 확인

,정책명,정책지원내용
130,청년과 어르신 주거공유(한지붕세대공감),"신청 시 1실당 100만원 이내 환경개선(도배, 장판 교체 등) 공사\n ㅇ (사업 대상)\n - 어르신 : 방 1실 이상 주택을 소유한 60세 이상 어르신\n - 학 생 : 대학(원) 재학생 및 휴학생\n"
152,『찾아가는 전세사기 피해예방』 교육 및 상담,#NAME?
360,청년세대 맞춤형 고충해소,1. 공공기관&middot;민간단체 등 업무협약을 체결하여 청년 취약계층 대상 지원사업 운영\n2. '달리는 국민신문고' 운영으로 찾아가는 고충 해결\n3. 제도 개선을 통해 청년세대 고충 유발요인 근본적 해결
446,귀농귀촌 임시거주시설 조성,젊은 귀농귀촌인이 적은 비용으로 안정적으로 장기체류할 수 있는 거주시설을 제공하여 농촌지역에 가족단위 귀농귀촌 유입 확산
944,대전시 전세사기피해주택 안전관리(소방점검) 지원,○ 지원내용 : 소방시설 작동점검 (비용부담 없음)\n○ 추진방법 : 관계인 입회 하에 관내 소방시설관리협회가 소방점검 협조
1283,2024년 전세피해 주택임차인 이사비 지원사업 안내,가구당 이주비 최대 160만원 실비 지원(1회에 한함)
1344,울산 희망상가 품은 청년희망주택 건립,"○ 위 치 : 울산광역시 중구 성안동 393-2\n\n○ 규 모 : 부지면적 1,311.6㎡, 연면적 1,805㎡, 지하 1층 지상 4층\n- 1층 : 희망상가(2호), 지역커뮤니티시설 \n- 2 ~ 4층 : 청년희망주택(36호)\n\n○ 사 업 비 : 7,369백만원(국 2,419 시 4,950)"
1345,울산 상안지구 행복주택 건립,"○ 위 치 : 울산광역시 북구 상안동 343 일원\n\n○ 세 대 수 : 행복주택 102세대(신혼부부, 사회초년생 81세대, 전체새대 80%)\n\n○ 사 업 비 : 37,965백만원(국 4,022 기금 5,363, 도시공사 28,580)"
2358,창원시 전세피해 예방 상담소 운영,□ 운영기간 : 2024. 2. 5.(월)∼\n□ 상담시간 : 월요일 오후 2시∼5시(주1회)\n□ 상담장소 : 시청 건축경관과(별관1층) 내\n□ 상담위원 : 17명(한국공인중개사협회 경남지부 소속 재능기부)\n□ 상담방법 : 방문 또는 전화상담
2992,어선청년임대사업 청년어업인 모집,"① 기존어업인의 어선(허가 포함)을 임대차계약을 통해 청년어업인에게 어선을 임대하며, 월 임차료의 50%를 공단에서 지원 \n② 청년어업인의 역량강화를 위한 사전실습·어업인 멘토링, 전문가 컨설팅 등 지원\n\n- 대상어선 : 전국 연안복합·연안통발·연안자망 어선\n- 임차료지원 : 어선임대차에 따른 월 임차료의 50%를 공단에서 임대인에게 대신 납부\n- 어선보험료 지원 : 임대용어선에 대한 어선보험 자기부담금 지원 \n- 어선어업 사전실습 : 전문업체를 통한 체계적 현장 실습 병행 추진\n- 우수어업인 멘토링 : 대상자의 어업활동 조기 정착을 위하여 지역 우수어업인과 멘토링 체결하여 멘토와 함께 일정기간 어획활동 수행\n- 전문가 컨설팅 : 어업·수산자원·수산물 유통 등 분야별 전문가의 컨설팅\n- 조업현황 모니터링 : 청년어업인 조업현황 온라인 보고 및 안전 관리"

In [144]:
df_rent[df_rent['지원형태'] == '금전 지원'][['정책명']].drop_duplicates().head(10)

                                   정책명
19                             대전청년하우스
113            2025 북구 청년 창업자 임대료 지원사업
127                  전월세 안심계약 도움서비스 운영
128                           청년 월세 지원
221                      음성군 청년월세 지원사업
222                         청년월세한시특별지원
264  대구형 청년희망주택(공공임대주택) 임대보증금 이자 지원 사업
265               대구형 청년희망주택 임대료 지원 사업
355                  청년사업자 점포 임대료 지원사업
372                      청년월세 특별지원(2차)

In [149]:
df_rent[df_rent['지원형태'] == '금전 지원'][['정책지원내용']].drop_duplicates().head(10)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          정책지원내용
19                                                                                                                                                    옛 외국인유학생기숙사 누리관을 리모델링하여 대전소재 사업장에서 근무하는 청년 근로자 대상 기숙사 조성 및 운영\n\n□ 위치 : 대전 유성구 엑스포로 97번길 103(도룡동)\n□ 규모 : 지상 1층 ~ 10층, 연면적 7,043㎡, 1실 18.41㎡\n□ 시설 : 공유라운지 등 공유공간 11개소\n□ 입주기간 : 2년\n※ 입주 기간 만기시 연장은 1년씩 최대 2회 가능 (입주 대기자가 없는 경우에 가능)\n□ 입주부담금\n  ○ 보증금 : 1,000,000원\n  ○ 임대료 : 250,000원\n  ○ 관리비 : 20,000원(인터넷 및 보안 등 이용료)\n  ○ 공과금  : 별도(전기, 가스, 수도 등)\n  ○ 정기주차권 : 10,000원 / 정기주차권은 주차 희망자에 한함. 입주민외 차량의 경우 정기주차권 발급불가\n□ 배치가구 : 침대, 냉장고, 옷장, 책상, 의자, 신발장, 시스템에어컨, IP-TV, WIFI\n※ 객실 난방방식은 천장형 에어컨 이용 방식임 (바닥에 별도 난방없음)
113                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     사업장 임대료 월 20만원 지원 (최대 4개월, 총 80만원) / 30명
127                                                                                                                                                                                                                                                                                                  ㅇ 사업 근거\n   - 서울시 사회적 가족도시 구현을 위한 1인가구 지원 기본조례 제11조\nㅇ 추진 경과\n   - 전월세 안심계약 도움서비스 추진계획 수립\t: ’22. 1월\n   - 5개 자치구 서비스 시범 운영\t \t\t  \t: ’22. 3월\n   - 25개 전 자치구로 서비스 확대\t\t\t: ’23. 5월\n   - 10개 자치구 토요일 운영\t\t\t\t: ’24. 4월\nㅇ 사업 기간 : ‘22. 3 ~ 계속\nㅇ 사업 대상 : 서울시 거주 또는 거주예정 1인가구(독립가구 예정자 포함)\nㅇ 사업 내용 : 자치구별 주거안심매니저가 주거정책 안내, 주거지 탐색, 집보기 및 계약시 동행지원\nㅇ 사 업 비  : 380백만원
128  ㅇ (사업 근거)\n   -「주거기본법」제15조(주거비 보조), 「청년기본법」제20조(청년 주거지원)\n   -「서울특별시 청년주거 기본 조례」제7조(청년주거사업),「서울특별시 청년 기본 조례」제13조(청년의 주거안정 등)\n ㅇ (추진 경과)\n   - 청년자율예산제에 따른 청년층 신규사업으로 요구(’19.9.)\n   - ’20년도「청년 월세 지원」사업 모집(’20.6.)\n   - ’21년도「청년 월세 지원」사업 모집(’21.3./’21.7.)\n   - ’22년도「청년 월세 지원」사업 모집(’22.6.)\n   - ’23년도「청년 월세 지원」사업 모집(’23.5./’23.9.)\n   - ’24년도「청년 월세 지원」사업 모집(’24.4.)\n ㅇ (사업 기간) ’25.1.1.~’25.12.31.(연례반복)\n ㅇ (사업 대상) 서울시 월세 거주 무주택 청년 1인 가구\n   - (연령 기준) 19~39세\n   - (소득 기준) 건강보험료 납입 기준 중위소득 150% 이하\n   - (재산 기준) 일반재산 1억 3천만원 이하, 자동차 2,500만원 미만\n   - (기타 조건) 임차보증금 8천만원 이하 및 월세 60만원 이하 \n ㅇ (사업 내용) 월 임차료 지원(20만원×12개월)   ※ 생애 1회 \n ㅇ (사 업 비) 45,817백만원
221                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             생애 1회, 월 최대 15만원, 최대 12개월 임차료 지원
222                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ❍ (지원대상) 부모와 별도로 거주하는 무주택 청년(만 19~34세) 청약통장가입필수  \n ❍ (소득기준) 청년 원가구의 소득이 기준 중위소득 100% 이하이면서 \n             청년 독립가구 소득이 기준 중위소득 60% 이하\n ❍ (지원내용) 1인 월 최대 20만원 임차료 지원(최대 24개월, 생애 1회)
264                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    표준임대보증금 범위내에서 대출이자 50% 지원
265                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     표준임대료 주변 시세의 50% 수준으로 지원
355                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              지원대상: 공고일 기준 18세 이상 45세 이하인 청년사업자(소상공인)로 통영시 관내에 사업장을 두고 거주 또는 거주예정인 자 \n\n지원내용: 월 임대료 범위 내에서 최대 30만원 한도(1인당 연 최대 150만원 지원)\n\n
372                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            □ 지원한도 : 실제 납부하는 임대료 범위 내에서 월 최대 20만원씩 24개월 동안 매월 분할 지원\n* 주거급여수급자도 월세지원 한도액 20만원에서 주거급여액을 차감하고 지원\n□ 지급기간 : 2024년 3월 ~ 2026년 12월

In [174]:
df_rent[df_rent['지원형태'] == '주택 제공'][['정책명']].drop_duplicates().head(10)

                               정책명
125                  청년안심주택 공급(매입)
131                   청년 매입임대주택 사업
184           상무지구 광주형 통합공공임대주택 건립
392            청년 신규 공무원 주거안정방안 마련
460                    용인청년 창업지원주택
588                경기행복주택 예비입주자 모집
650      24년 2차 든든전세주택 입주자 모집 통합공고
655  충남 아산읍내  LH 영구임대주택 예비입주자 모집공고
656     광주각화 LH 영구임대주택 예비입주자 모집 공고
668   부천원종 B2블록 신혼희망타운 행복주택 입주자 모집

In [155]:
pd.set_option('display.max_colwidth', None)
df_rent[df_rent['지원형태'] == '주택 제공'][['심사방법내용']].drop_duplicates()

                                                                                                                                                                                                                                                                                                                                                                                                                                                          심사방법내용
125                                                                                                                                                                                                                                                                                                                                                                                                                                                          NaN
460                                                                                                                                                                                                                                                                                                                                                                                                                                              용인시청 홈페이지 공고 참조
650                                                                                                                                                                                                                                                                                                   - 신청접수 : 2024.11.11 ~ 11.13\n- 서류제출대상자 발표 : 11.14\n- 서류제출 : 2024.11.15 ~ 11.19\n- 자격검증 : 2024.11.20 ~ 12.13\n- 당첨자 및 예비입주자 발표 : 2024.12.16\n- 계약체결 : 별도 안내
655                                                                                                                                                                                                                                                                                                                                                                                                              예비입주자 발표 : ‘25.02.20.(목) 16:00 이후\n계약안내 : 개별 통보
656                                                                                                                                                                                                                                                                                                                                                                                                               예비입주자 발표 : ‘25.03.14 (금) 17:00 이후\n계약안내 : 개별안내
668                                                                                                                                                                                                                                                                                                                           서류제출대상자 발표: 24.11.21(목) 17시 이후\n서류제출 : 24.11.22(금) ~ 11.28.(목)\n당첨자 발표 : 25.4.3.(목) 17시 이후\n계약체결 :  25.4.15.(화) 10시 ~ 4.17.(목) 17시
759                                                                                                                                                                                                                                                                                                                                                                                                                    예비입주대상자 발표: 2025.03.13.(목)16:00 이후 LH홈페이지
861                                                                                                                                                                                                                                                                                                                                                                                                                    예비입주대상자 발표: 2025.03.13.(목) 16:00이후 LH홈페이지
945                                                                                                                                                                                                                                                                                                                                                                                                                    예비자순번 발표: 12.13(금) (17:00이후)\n계약체결: 개별 안내
1004                                                                                                                                                                                                                                                                                                                                                                                                                              당첨자 및 예비입주자 순위발표 : 2024.12.13.
1262                                                                                                                                                                                                                                                                                ○ 공급일정\n- 청약접수일 : 2024. 8. 7.(수) 10:00 ~ 2024. 8. 9.(금) 17:00\n- 서류심사대상자 발표 : 2024. 8. 16.(금)\n- 심사대상자 서류제출기간: 2024. 8. 26.(월) ~ 2024. 8. 28.(수)\n- 당첨자발표 : 2024. 11. 25.(월)
1337                                                                                                                                                                                                                                                                                                                                                                                                                                                           -
1819  □ 당첨자 발표\n[1순위] 2024년 10월중 (당첨자 홈페이지 게시 및 개별통보)\n[2·3순위] 2024년 10월중 (당첨자 홈페이지 게시 및 개별통보)\n- 당첨자의 주소변경 등으로 계약안내문과 계약금고지서가 도달되지 아니하는 사례가 있으므로 신청자는 당첨자 여부를 필히 확인 요함\n- 당첨사실을 확인하지 못하여 미계약으로 인한 당첨취소 등의 불이익에 대한 책임은 신청자 본인에게 있음\n- 당첨자로 발표되었더라도 입주 부적격자임을 통보받아 부적격사유에 대한 소명절차가 완료되지 않은 경우에는 계약체결이 불가함\n- 공급주택의 입주자 모집공고일 이후 입주자의 퇴거 등으로 추가로 공가가 발생한 경우에는 추가된 세대수를 포함하여 해당주택의 예비자에게 공급함\n- 당첨자 발표는 홈페이지에 게시되며 당첨 사실 확인을 위하여 성명, 생일이 게시됨을 알려드립니다.(Ex 홍*동, 0918)
2205                                                                                                                                                                                                                                                                                                                                                                                             - 심사 : 모집 공고 참고\n- 발표예정일: 2024. 8. 9.(금)\n ※ 심사 일정에 따라 변경될 수 있음
2382                                                                                                                                                                                                                                                                                                                                ○ 소득심사 및 사업계획서 등 서류심사 결과에 따라 입주대상자 선정 후 광진구청 및 서울주택도시공사 홈페이지 발표(수시)\n○ 당첨자발표: 2024년 6월(심사 일정에 따라 변경될 수 있음)\n\n* 상세내용은 공고문 참조
2643                                                                                                                                                                                                                                                                                                                                                                                                 발표예정일 : 2024. 7. 5.(금)\n 발표방법 : 성북구청 홈페이지 공고 게시 및 SMS 개별 통보
3330                                                                                                                                                                                                                                                                                                                                                                                                      - 당첨자 발표 : `24.5.31. 17시 이후\n- 계약 체결 : `24.6.18. ~ 25.

In [156]:
# 보조금에 무엇이 있는지
# 컬럼 안의 텍스트를 줄임 없이 출력
pd.set_option('display.max_colwidth', None)
print(df_grant[['정책명', '정책지원내용']])

                             정책명  \
0                        주거안정장학금
24              속초시 청년 이사비용 지원사업
216         청년취업자 및 청년농업인 주거비 지원
404               모다드림 청년통장 지원사업
490          장흥군 신혼부부 웨딩포토비 지원사업
492                신혼부부 이사비 지원사업
496            강진품애 청년 주거비 지원 사업
506   청년 및 주거취약계층 주택 중개수수료 지원 사업
1031               해남형 청년 주거비 지원
3204  대학생 주거 지원(서서울관, 동서울관, 청주관)

                                                                                                                                                                                                                                                                                                                                                                                                                                                          정책지원내용
0     □ 지원금액: 월 최대 20만 원\n※ 단, 방학 중(7~8월, 1~2월)에는 지원하지 않으며, 계절학기를 수강하는 경우에는 방학 중에도 장학금 지원 가능\n\n□ 지원범위: 월 20만 원 한도 내 학생이 지출한 주거 관련 비용 포괄 지원\n- 주거 관련 비용 : 임차료*(전‧월세, 보증금** 등), 주거 유지‧관리비(수선유지비, 공동주택관리비 등), 수도‧연료비(상하수도, 전기, 가스, 열, 등유, 연탄 등), 주택임차‧저당차입금 이자상환액 등\n※ 단, 보증금 월환산차임은 주택임차차입금 이자와 중복 청구할 수 없음 (월세 대출 이자는 가능)\n* 임차료는 주택, 기숙사, 고시원 등 유형을 불문하고 거주를 목적으로 지급하는 사용료 모두 해당\n** 보증금의 경우 「주거급여 실시에 관한 고시」 제7조제3항에 따른 보증금의 환산율(연 4%)을 준용하여 월 환산 후 월 차임으로 산정함
24                                                                                   ㅇ (사업 기간) ’25. 1. ~ 예산소진 시\n ㅇ (사업 대상) 2025. 1. 1.이후 관외에서 속초시로 또는 관내 전입하는 무주택 청년가구\n    - (연령 기준) 18세 ~ 45세\n    - (소득 기준) 중위소득 150% 이하\n    - (기타 조건)\n     * 청년이 세대주 및 전·월세 계약자 본인이어야 함\n     * 주민등록상 동거인(가족 등) 이 있는 경우에도 지원 가능\n     * 외국인, 재외국민 등은 지원대상 아님\n ㅇ (사업 내용) 이사비 및 부동산 중개수수료 포함하여 1인당 최대 50만원 이내 실비 지원 (생애 1회)\n    -이사비용 : 차량대여비, 운반비, 포장비\n    -부동산 중개수수료\n
216                                                                                                                                                                                                                                   청일 기준 군에 주민등록을 두고 있으며, 관내 중소기업･사회복지시설 취업 또는 농업경영체등록 후 5년이 경과하지 않은 청년 근로자 또는 전업 청년농업인(만19세 ~ 만49세 이하)에게 전・월세 비용 월 100,000원, 최대 3년간(분기별 지급)\n    ※ 전・월세 임대차계약서 기준 임차인이 청년 본인임에 한정 주거급여 등 기타 유사 괴산군에서 시행한 주거사업 지원을 받고 있는 자 제외
404                                                                                                                                                                                                                                               지원내용 \n매월 청년이 20만원을 적립하면 경남도와 시군에서 20만원을 추가로 적립하여 청년이 2년간 재직할 경우 만기금 960만원과 이자를 청년 근로자에게 지급\n- 월 적립 40만원(도ㆍ시군 월 20만원, 청년 20만원)\n- 만기액 960만원(도&middot;시군 각 240만원, 청년 480만원)\n\n지원규모\n상반기와 하반기 500명씩 총 1,000명 지원
490                                                                                                                                                                                                                                                                                                                                     ❍ 지원대상\n   - &rsquo;23. 1. 1.이후 혼인하고 장흥군 주소등록한 부부 모두 49세 이하 신혼부부\n ❍ 신청기한 : 혼인신고일로부터 6개월 이내\n ❍ 지원금액 : 최초 1회, 최대 30만원 지원
492                                                                                                                                                                                                                                                                                                                                        ❍ 지원대상\n   - &rsquo;23. 1. 1.이후 혼인하고 장흥군 주소등록한 부부 모두 49세 이하 신혼부부\n ❍ 신청기한 : 이사일로부터 3개월 이내\n ❍ 지원액 : 최초 1회, 최대 50만원 지급
496                                                                                                                                                                                                                                                                                                                           강진군으로 전입신고 하고, 3개월 이상 거주중인 만19세~45세 청년이며 전세 1억원 이하 또는 월세 60만원 이하 주택에 거주, 기준 중위소득 60~160% 이하인 자에게 1인가구 20만원, 2인가구 이상 25만원을 매월 지급 \n
506                                                                                                                                                                                   \t○ 청년 및 주거취약계층을 위한 주택 중개수수료 지원사업 추진계획 입니다.\n - 시행일 : 2025. 1. 1.\n - 지원대상 : 청년, 신혼부부, 수급자, 차상위계층, 한부모가족\n                  (청년 및 신혼부부는 무주택자에 한함)\n - 지원내용 : 주택 중개보수 30만원 이내\n                  (2년 1회, 최대 3회 지원)\n - 지원요건 : 3억원 이하의 주택 매매&middot;전월세 계약\n - 사업예산 : 250백만원
1031                                                                                                                                                                                                                                                                                                                                                 ○ 공고일 기준 관내 주소지 등록 청년(18 ~ 49세)\n○ 중위소득 150%이내\n○ 전 &middot; 월세 계약으로 주거중인 자 월 10만원 정액지원(연 최대 100만원 / 생애 3회)
3204                                                                         ❍ (사업대상) 대학교 재학생, 신입생\n ❍ (지원자격) \n  - (지역) 본인 또는 친권자의 주소가 충청북도 이내인 자(최소1년 이상)\n  - (학적) 수도권(서·동서울관) 또는 충북(청주관) 지역 소재 대학교 학생\n  - (성적) 재학생 : 직전년도 성적 우수자 순신입생 : 고교 내신성적과 대입수능성적 우수자 순   \n ❍ (선발기준) 학업성적 60%, 생활정도 40%, 가산점 5점\n ❍ (사업내용) 장학시설 관리·운영, 입사생 선발과 생활지도, 면학 분위기 조성 등\n   - 기숙사, 정독실, 정보검색실, 회의실, 체력단련장, 휴게실 등\n ❍ (이 용 료) 서·동서울관(월 25만원), 청주관(월 17만원)\n   ※ 입사등록비 5만원 별도

1. 주거 분류해서 포함 안되었는거 확인
- 100개 정도 봤을 때 포함 안되는건 없지만 이게 포함인가? 라고 생각드는건 있음
ex) 공방 창업지원
맞춤형 농지지원
전세사기 예방 법률&심리지원 사업 <br><br>

2. 대출 안에 조건 분석 ( 어떤 조건이 있어야 하지?)
- 대출 상품은 청년/신혼부부로 나뉘어지는데 신혼부부 정책이 월등히 많다
- 청년이냐 신혼부부냐 구분 필요 (청년/신혼부부/ 확인 필요) 
- 청년/신혼부부 안에서 정책 분류를 하면 대부분이 대출이자지원이고 나머지는 ㄹㅇ 월세대출, 전세대출이다 . -> ㄹㅇ 대출을 원하는지, 대출이자지원을 원하는지

- 지역 : 지방은 지역이 중요 수도권은 지역 조건 거의 없음
- 나이는 범위가 넓음 (18~45) 
- 소득이 조건에서 가장 중요, 하지만 데이터파일에는 명확히 소득기준을 나타내는 데이터가 많이 없음, 따로 사이트에서 확인해야 하는 경우가 많음
   -> 그럼 이럴때는 어떤 데이터를 달라고해야하는가? 그냥 url 참고하라고 해야하는가? <br><br>

3. 전월세 안에 어떤 걸 지원하는지
- 주택 제공과 금전 지원으로 나뉘는데 금전 지원이 월등히 많음 -> 사용자에게 금전을 원하는건지 주택을 원하는건지 물어볼 필요가 있음.<br><br>

4. 보조금에 어떤 것들이 있는지<br>
청년취업자 및 청년농업인 주거비 지원   
모다드림 청년통장 지원사업   
 장흥군 신혼부부 웨딩포토비 지원사업   
신혼부부 이사비 지원사업   
강진품애 청년 주거비 지원 사업   
 청년 및 주거취약계층 주택 중개수수료 지원 사업

Q1. 신혼부부인가요?

Q2. 지역은 어디인가요? (서울, 경기, 지방 등)

Q3. 주거 관련해서 어떤 게 더 필요한가요?

월세 대출 / 대출이자 지원 / 주택(임대, 기숙사 등) / 보조금 (ex. 이사비)

Q4. (선택) 나이, 소득 조건 공유 가능하신가요

In [165]:
import re

def extract_province(region_text):
    if pd.isna(region_text):
        return '기타'
    match = re.search(r'(서울|경기|인천|부산|대구|광주|대전|울산|세종|강원|충북|충남|전북|전남|경북|경남|제주|충청|경상|전국)', region_text)
    return match.group(0) if match else '기타'

In [169]:
def map_to_area(province):
    if province == '서울':
        return '서울'
    elif province in ['경기', '인천']:
        return '수도권'
    elif province == '강원':
        return '강원'
    elif province in ['경북', '경남', '부산', '대구', '울산','경상']:
        return '경상도'
    elif province in ['충북', '충남', '대전', '세종','충청']:
        return '충청도'
    elif province == '제주':
        return '제주도'
    elif province == '전국':
        return '전국'
    else:
        return '기타'

In [170]:
# 시·도 추출
df_housing['시도'] = df_housing['정책거주지역코드'].apply(extract_province)

# 도 단위 지역 그룹 생성
df_housing['도지역'] = df_housing['시도'].apply(map_to_area)

In [175]:
df_housing['시도']

0       전국
3       서울
4       서울
19      전국
22      전국
        ..
3428    전국
3429    전국
3430    전국
3436    전국
3461    전국
Name: 시도, Length: 332, dtype: object

In [176]:
# 전체 정책 수 (도별)
print(df_housing['도지역'].value_counts())

# 도별 주거세부분류 분포
area_pivot = pd.pivot_table(
    df_housing,
    values='정책번호',
    index='도지역',
    columns='주거세부분류',
    aggfunc='count',
    fill_value=0
)

area_pivot

도지역
경상도    117
수도권     69
기타      39
전국      36
서울      31
충청도     26
강원       7
제주도      7
Name: count, dtype: int64

주거세부분류  기타  대출  보조금  전월세
도지역
강원       1   3    1    2
경상도     17  23    1   76
기타       8   5    4   22
서울       8   3    0   20
수도권     10  30    0   29
전국       3   5    1   27
제주도      0   2    1    4
충청도      4   5    2   15